"""生成 Week 1-4 的课程 .ipynb。"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _course_helpers import PATH_SETUP, code, md, save


# ============================================================
# Week 1 · 数据 + Tokenizer
# ============================================================
W1 = [

md(
    '# Week 1 · 数据 + Tokenizer',
    '',
    '> **本周一句话**:把 chinese-poetry 仓库的 5 万首唐诗,变成 train.pt / val.pt / tokenizer.pkl 三个文件,后面所有 Week 都在这三个文件之上。',
    '',
    '没有模型,没有训练。但**数据 pipeline 跑通是后面 7 周的基石** —— 任何 bug 在这里没修干净,后面所有 loss 都不可信。',
),

md(
    '## 0. 本周目标',
    '',
    '学完之后你应该能:',
    '- 解释一份原始唐诗 JSON 是怎么变成模型能吃的 `torch.Tensor` 的',
    '- 知道字符级 tokenizer vs BPE 各自的取舍',
    '- 看懂 `get_batch` 里那个 `torch.randint(len(d) - block_size - 1)` 为什么是这个数字',
    '- 一条命令 `python data/prepare.py` 复现整套数据',
    '',
    '**产物**:',
    '| 文件 | 大小 | 含义 |',
    '|---|---|---|',
    '| `data/processed/tang_poems_clean.txt` | 11 MB | 清洗后的纯文本 |',
    '| `data/processed/tokenizer.pkl` | 0.2 MB | `stoi` / `itos` 字典 |',
    '| `data/processed/train.pt` | 32 MB | 编码后的训练张量(int64) |',
    '| `data/processed/val.pt` | 4 MB | 编码后的验证张量 |',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Python list/dict、文件 IO',
    '- `torch.Tensor` 基本操作:`shape`、`dtype`、索引、`torch.stack`',
    '- 知道 GPU 显存的概念',
    '',
    '**不必备(看不懂可以跳过)**:',
    '- BPE / SentencePiece 算法细节',
    '- HuggingFace tokenizers 库 —— 我们故意不用,从零写最简单的字符级版本',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 数据 pipeline 五步走',
    '',
    '```',
    '  ┌─────────────┐    ┌─────────────┐    ┌─────────────┐',
    '  │  下载       │ → │  合并        │ → │  清洗        │',
    '  │ git clone   │    │ JSON→txt    │    │  去噪音字符 │',
    '  └─────────────┘    └─────────────┘    └─────────────┘',
    '         ↓                                       ↓',
    '   raw/chinese-poetry/             processed/tang_poems_clean.txt',
    '',
    '         ┌─────────────┐    ┌─────────────────────────────┐',
    '         │  建词表     │ → │  编码 + 切分                  │',
    '         │  stoi/itos  │    │  text→tensor→train/val      │',
    '         └─────────────┘    └─────────────────────────────┘',
    '              ↓                       ↓',
    '       tokenizer.pkl         train.pt + val.pt',
    '```',
    '',
    '每一步都对应一个独立的 `.py` 文件,可以单独跑也可以用 `data/prepare.py` 一键串起来。',
    '**为什么拆这么细**:任何一步出问题,只需要重跑那一步 —— 数据 pipeline 是项目里最容易引入隐藏 bug 的环节,组合的边界要清楚。',
),

md(
    '### 2.2 为什么字符级 tokenizer',
    '',
    '字符级 = 一个汉字一个 token。统计后 `vocab_size = 9563`(唐诗里所有不重复的字符 + 标点 + 换行)。',
    '',
    '**为什么不用 BPE**?',
    '',
    '| 维度 | 字符级 | BPE |',
    '|---|---|---|',
    '| 实现复杂度 | 5 行 Python | 需要训练合并规则,几百行 |',
    '| 中文友好度 | ★★★(一字一意,天然 token) | ★★(子词概念在中文里不自然) |',
    '| 词表大小 | 9k(唐诗)~ 14k(唐宋全)| 通常 32k+ |',
    '| 学习成本 | 看 30 秒 | 看半天 |',
    '',
    '**结论**:Week 1-7 用字符级,把概念跑通;真要工业级再换 BPE 不晚。',
),

code(
    '# 5 行字符级 tokenizer 的完整实现',
    'text = "床前明月光，疑是地上霜"',
    'chars = sorted(set(text))',
    'stoi = {c: i for i, c in enumerate(chars)}',
    'itos = {i: c for c, i in stoi.items()}',
    '',
    'print(f"vocab_size = {len(chars)}")',
    'print(f"encoded = {[stoi[c] for c in text]}")',
    'print(f"round-trip = {\'\'.join(itos[i] for i in [stoi[c] for c in text])}")',
),

md(
    '### 2.3 train/val 切分',
    '',
    '我们简单按时间顺序切 90/10:前 90% 训练,后 10% 验证。',
    '',
    '**为什么不随机切**?语言数据有强时序结构 —— 同一首诗的前后两句不能一句在 train、一句在 val,否则验证集 "泄露"。按位置切是最简单干净的隔离。',
    '',
    '**val 拿来干什么**?每隔几百步算一次 `estimate_loss(val)`,看 val loss 走势:',
    '- val 跟 train 一起降 → 在学规律',
    '- val 卡住、train 还在降 → **开始过拟合**',
    '- val 反弹 → 大概率过拟合 / lr 太大 / 数据有问题',
    '',
    'val loss 是后面 7 周里最常看的数字,做个心理准备。',
),

md(
    '### 2.4 get_batch 的滑动窗口采样',
    '',
    '这是 Week 1 里**最容易讲不清楚**的一个函数。完整代码:',
    '',
    '```python',
    'def get_batch(split):',
    '    d = train_data if split == "train" else val_data',
    '    ix = torch.randint(len(d) - block_size - 1, (batch_size,))',
    '    x = torch.stack([d[i : i + block_size]     for i in ix])',
    '    y = torch.stack([d[i + 1 : i + 1 + block_size] for i in ix])',
    '    return x, y',
    '```',
    '',
    '**关键三句**:',
    '',
    '1. `torch.randint(len(d) - block_size - 1, (batch_size,))`',
    '   抽 `batch_size` 个随机起点,每个起点要保证后面还有 `block_size + 1` 个字符可取 —— 所以最大起点是 `len(d) - block_size - 1`。',
    '',
    '2. `x = d[i : i + block_size]`',
    '   从起点取连续 128 个字作为输入。',
    '',
    '3. `y = d[i + 1 : i + 1 + block_size]`',
    '   错位一个字作为目标 —— 这就是"下一字预测"的本质:在每个位置,模型看 x[0:t+1],预测 y[t] = x[t+1]。',
    '',
    '**为什么是 -block_size - 1 而不是 -block_size**?因为 y 比 x 还要多看一个未来字,边界少一个。这里出错最常见的表现是训练偶尔崩在 "IndexError: index out of bounds"。',
),

code(
    '# 演示 get_batch 的输出形状',
    'import torch',
    '',
    'data = torch.arange(100, 200)   # 假装是 100 个 token 的连续数据',
    'block_size, batch_size = 8, 3',
    '',
    'ix = torch.randint(len(data) - block_size - 1, (batch_size,))',
    'x = torch.stack([data[i : i + block_size]     for i in ix])',
    'y = torch.stack([data[i + 1 : i + 1 + block_size] for i in ix])',
    '',
    'print(f"起点: {ix.tolist()}")',
    'print(f"x.shape = {x.shape}  (batch_size, block_size)")',
    'print(f"y.shape = {y.shape}")',
    'print(f"x[0] = {x[0].tolist()}")',
    'print(f"y[0] = {y[0].tolist()}   ← 注意 y[0][t] == x[0][t+1]")',
    'print(f"对齐验证: {torch.equal(x[0, 1:], y[0, :-1])}")',
),

md(
    '## 3. 代码地图',
    '',
    '按"读代码的顺序"列,不是字母序:',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `configs/config.py` | 80 | 所有路径常量,先看一眼 |',
    '| `data/download.py` | 25 | `git clone` chinese-poetry |',
    '| `data/merge.py` | 35 | 把所有 JSON 里的 `paragraphs` 拼成一个大 txt |',
    '| `data/clean.py` | 25 | 去掉数字 / 几何符号 / 多余换行 |',
    '| `tokenizer/tokenizer.py` | 40 | `CharTokenizer` 类,带 `save/load` |',
    '| `tokenizer/build.py` | 35 | 读清洗后文本 → 建 tokenizer → 编码 → 切分 → 存 |',
    '| `data/prepare.py` | 30 | 一键跑完上面 4 步 |',
    '| `train/utils.py:get_batch` | 15 | 上面 2.4 节那个滑动窗口 |',
    '',
    '`prepare.py` 是入口;`utils.py:get_batch` 是后面所有训练循环都会用的工具,重点看。',
),

md(
    '## 4. 动手做',
    '',
    '**先激活 venv**(假设你已经 `uv sync` 过):',
    '',
    '```powershell',
    '.venv\\Scripts\\Activate.ps1',
    '```',
    '',
    '然后:',
),

code(
    '# 一键跑完整 pipeline (从 courses/ 目录跑)',
    'import subprocess',
    'subprocess.run(["python", "../data/prepare.py"], check=True)',
),

md(
    '**预期输出**(关键行):',
    '',
    '```',
    '[1/4] 下载数据',
    '  clone https://github.com/chinese-poetry/...',
    '',
    '[2/4] 合并 JSON',
    '  准备处理 58 个文件',
    '  共 57603 首诗,3,993,966 字符',
    '',
    '[3/4] 清洗噪音',
    '  清洗前: 3,993,966 字符, vocab=9583',
    '  清洗后: 3,987,419 字符, vocab=9563',
    '',
    '[4/4] 构建 tokenizer + 编码切分',
    '  vocab_size = 9563',
    '  train: torch.Size([3588677])',
    '  val:   torch.Size([398742])',
    '```',
    '',
    '**怎么判断跑对了**:',
    '- `vocab_size` 是 **9563**(±2,版本差异)',
    '- `train` 张量约 360 万 token,`val` 约 40 万',
    '- 比例约 9:1',
    '- 总大小 `train.pt + val.pt` 约 64 MB',
    '',
    '任何一个数字差一个数量级就要看 log,别往下走。',
),

code(
    '# 验证产物:加载 tokenizer 编码两个字看看',
    'import sys, pathlib',
    'sys.path.insert(0, str(pathlib.Path().resolve().parent))',
    '',
    'from tokenizer.tokenizer import CharTokenizer',
    'from configs.config import TOKENIZER_FILE',
    '',
    'tok = CharTokenizer.load(TOKENIZER_FILE)',
    'print(f"vocab_size = {tok.vocab_size}")',
    'print(f"\'月\' 的 ID = {tok.stoi[\'月\']}")',
    'print(f"\'床前明月光\' 编码 = {tok.encode(\'床前明月光\')}")',
    'print(f"还原 = {tok.decode(tok.encode(\'床前明月光\'))}")',
),

md(
    '## 5. 自测题(不给答案,自己脑子里答)',
    '',
    '**A. 数据**',
    '- A1 `chinese-poetry` 仓库的目录结构是什么?`paragraphs` 字段长什么样?',
    '- A2 清洗为什么把 `0123456789` 这种数字字符也去掉?去之前 vocab 是多少,去之后是多少?',
    '- A3 如果不调 `re.sub(r"\\n{3,}", "\\n\\n", text)`,会发生什么?对训练有什么影响?',
    '',
    '**B. Tokenizer**',
    '- B1 `stoi` 和 `itos` 是不是一定要从同一份数据构建?如果训练用的 `stoi` 和推理用的 `itos` 来自不同文本,会怎样?',
    '- B2 字符级 tokenizer 对古诗友好,对现代中文(包含表情符号 / 罕见字)友好吗?',
    '- B3 我们的 vocab 里有换行符 `\\n` 吗?换行符的 ID 是几?它在模型里起什么作用?',
    '',
    '**C. get_batch**',
    '- C1 `block_size = 128` 意味着模型最多能看几个字的上文?如果上文超过 128 会怎样?',
    '- C2 `batch_size = 32` 是什么意思?改成 64 / 128 训练会怎么变?',
    '- C3 `torch.randint(low=0, high=N, size=(B,))` 抽出来可能有重复,这对训练有问题吗?',
    '',
    '**D. 切分**',
    '- D1 为什么不能把所有诗打乱再 90/10 切?和 Week 5(`prepare_v2.py`)里 `random.shuffle(poems)` 又有什么不同?',
    '- D2 验证集只有训练集的 1/9,够吗?如果 val 只剩 1000 token 会怎样?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`tensor view` 让 .pt 文件翻倍**',
    '',
    '```python',
    'data = torch.tensor(...)         # 假设 64 MB',
    'train = data[:int(0.9*len(data))]   # 是个 view,共享底层 storage',
    'val   = data[int(0.9*len(data)):]   # 也是 view,共享',
    'torch.save(train, "train.pt")    # ← 实际写入了整个 64 MB storage,不是 58 MB!',
    'torch.save(val, "val.pt")        # ← 也写入了整个 64 MB!',
    '```',
    '',
    '**修复**:存之前 `.clone()` 一下,切断 view 共享。我们的 `tokenizer/build.py` 走的是先编码再 slice 的路径,默认不会触发这个;但 Week 5 的 `prepare_v2.py` 有显式 `.clone()` 防御。',
    '',
    '**坑 2:Windows GBK 控制台 + emoji 直接崩**',
    '',
    '所有 `print("✅ 完成")` 在默认 cmd / PowerShell 里会 `UnicodeEncodeError: gbk codec`。',
    '修复:不用 emoji,改成 `[OK]`;或者运行前 `chcp 65001` 切 UTF-8;或者 `$env:PYTHONIOENCODING="utf-8"`。',
    '',
    '**坑 3:`stoi[c]` 遇到训练集没出现过的字符 → KeyError**',
    '',
    '生成时如果 prompt 含训练集没见过的字(比如简体字 → 繁体训练),会崩。',
    '应对:加 try/except 或加 `<|unk|>` token。Week 6 引入特殊 token 时会顺便讨论。',
    '',
    '**坑 4:`paragraphs` 字段在某些 JSON 里是空 list**',
    '',
    '部分残卷的 JSON 没有 `paragraphs` 字段(只有 `title`)。我们的 `data/merge.py` 用了 `poem.get("paragraphs", [])`,空 list 自动跳过 —— 但你要清楚这是有意的过滤,不是 bug。',
),

md(
    '## 7. 进入 Week 2 前',
    '',
    '现在你应该:',
    '- ☑ 跑完了 `data/prepare.py`,`data/processed/` 下有 4 个文件',
    '- ☑ 能用 `tokenizer.encode("月")` 拿到一个数字',
    '- ☑ 能解释 "为什么 `randint(len(d) - block_size - 1)` 是这个减法"',
    '',
    '满足以上 3 条就开 Week 2。任何一条还模糊的,**别往下走**,回到对应小节再读一遍 + 跑一遍代码。',
    '',
    'Week 2 我们正式上 Bigram → 单头 Attention → 多头 + FFN + 残差 → 6 层 Transformer,看 val loss 从 5.43 一路降到 4.14。',
),

]

save('01_data_and_tokenizer.ipynb', W1)


# ============================================================
# Week 2 · Transformer 基础(Bigram → 6 层 GPT)
# ============================================================
W2 = [

md(
    '# Week 2 · Transformer 基础',
    '',
    '> **本周一句话**:从一个不带任何"注意力"的 Bigram 查表 baseline 开始,逐步加上 token/pos embedding、单头 attention、多头、FFN、残差、LayerNorm、深度堆叠,看 val loss 从 5.43 一路降到 4.14。',
    '',
    '这是项目最厚的一周。学完之后你写的代码就是一个能 work 的 GPT。',
),

md(
    '## 0. 本周目标',
    '',
    '4 个版本的演进:',
    '',
    '| 版本 | 关键改动 | 参数量 | val loss | 写出的诗 |',
    '|---|---|---|---|---|',
    '| Bigram | 一张 (V, V) 查表,无任何上下文 | 91 M | **5.43** | 单字接龙,毫无连贯 |',
    '| v0.1 | + token/pos embed + 单头 attention(16 维)| 0.79 M | 6.03 | **反而退步** —— 容量瓶颈 |',
    '| v0.2 | + 多头(4 头)+ FFN + LayerNorm + 残差 | 2.67 M | 5.10 | 击穿 Bigram,初见句式 |',
    '| v0.3 | + 6 层 Block + GPT-2 风格初始化 | 6.37 M | **4.14** | 开始押韵、有意境 |',
    '',
    '**注意 v0.1 的"反而退步"** —— 这是教学上故意的失败案例。比起直接给你成功的代码,看到一次失败 + 知道为什么失败,理解会深得多。',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 1 跑通(数据 + tokenizer + get_batch)',
    '- 矩阵乘法的形状变换:`(A, B) @ (B, C) = (A, C)`',
    '- 知道什么是"梯度下降"、"反向传播"、"交叉熵"',
    '',
    '**这周第一次遇到的话**:',
    '- `nn.Embedding`、`nn.Linear`、`nn.LayerNorm`、`nn.Dropout`、`F.softmax`、`F.cross_entropy`',
    '- `register_buffer` vs `nn.Parameter` 的区别(在 6.2 节讲)',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 Bigram 是什么',
    '',
    '最朴素的语言模型:**只看上一个字预测下一个字**,完全忽略更远的上下文。',
    '',
    '实现就一张 `nn.Embedding(vocab_size, vocab_size)` 表 —— 输入是 token id,直接查出来一行 `vocab_size` 维向量当 logits。',
    '',
    '```python',
    'class BigramModel(nn.Module):',
    '    def __init__(self, V):',
    '        super().__init__()',
    '        self.lut = nn.Embedding(V, V)   # 91M for V=9563',
    '    def forward(self, x):',
    '        return self.lut(x)              # (B, T, V)',
    '```',
    '',
    '**为什么 baseline 重要**?它给后面所有模型一条"如果你比我还差,说明你白搭了 attention"的底线。Bigram 的 val 5.43 就是这条线。',
),

md(
    '### 2.2 单头 Self-Attention(v0.1 的失败)',
    '',
    '加上位置编码 + 单头 attention 之后,模型理论上能"看上文"了。但我们故意把 head_size 设成 16(很小),结果 val loss 是 **6.03 比 Bigram 还差**。',
    '',
    '**为什么会更差**?',
    '',
    '- Bigram 直接用 `(V, V) = (9563, 9563)` 的大表,能"死记硬背"所有 bigram pattern',
    '- v0.1 的 attention 只有 16 维信息瓶颈,所有上下文压成 16 个数,**还不如直接查表**',
    '',
    '**教学价值**:看到一个反例,理解"加了 attention ≠ 必然变好",要看容量配不配。',
    '',
    '**Attention 的数学公式**(逃不开):',
    '',
    '$$\\mathrm{Attention}(Q, K, V) = \\mathrm{softmax}\\left(\\frac{Q K^\\top}{\\sqrt{d_k}}\\right) V$$',
    '',
    '`Q / K / V` 都是同一个输入 `x` 经过 3 个独立 `Linear` 投影出来的(self-attention 的 "self" 就这个意思)。',
),

code(
    '# 一头 self-attention 的最小实现(对照 model/minigpt_v01.py:SingleHead)',
    'import torch',
    'import torch.nn as nn',
    'import torch.nn.functional as F',
    '',
    'B, T, C = 2, 4, 8     # batch=2, seq=4, embed=8',
    'head_size = 4',
    'x = torch.randn(B, T, C)',
    '',
    'Wq = nn.Linear(C, head_size, bias=False)',
    'Wk = nn.Linear(C, head_size, bias=False)',
    'Wv = nn.Linear(C, head_size, bias=False)',
    '',
    'q, k, v = Wq(x), Wk(x), Wv(x)         # 各 (B, T, head_size)',
    'scores = q @ k.transpose(-2, -1) * head_size ** -0.5   # (B, T, T)',
    '',
    'tril = torch.tril(torch.ones(T, T))',
    'scores = scores.masked_fill(tril == 0, float("-inf"))  # causal mask',
    'weights = F.softmax(scores, dim=-1)',
    'out = weights @ v                      # (B, T, head_size)',
    '',
    'print(f"weights[0]:\\n{weights[0]}")',
    'print(f"\\n注意上三角全是 0(被 -inf softmax 压成 0)—— 这就是 causal mask")',
),

md(
    '### 2.3 Causal mask 为什么是 -inf 而不是 0',
    '',
    'softmax 公式 `exp(x) / sum(exp(x))`:',
    '- 如果填 `0`,`exp(0) = 1` —— 仍然分到权重,模型偷看未来',
    '- 如果填 `-inf`,`exp(-inf) = 0` —— 权重严格 0',
    '',
    '只有 `-inf` 才能彻底"屏蔽"未来位置。',
    '',
    '**上三角还是下三角**?`scores[i][j]` 表示位置 i 看位置 j。',
    '- 列号 > 行号(上三角)= "看未来" → 屏蔽',
    '- 列号 ≤ 行号(下三角)= "看当前及过去" → 保留',
),

md(
    '### 2.4 为什么 scores 要除 √d_k',
    '',
    '不除会怎样?`q @ k.T` 的结果方差和 `d_k` 成正比,`d_k` 大了之后 scores 会变得很大。',
    '',
    'softmax 输入数字之间差距大时,**会一边倒**(一个位置吃 99% 权重,其他全是 0):',
    '- 信息瓶颈:模型只看一个位置',
    '- 梯度消失:softmax 接近 one-hot 时对输入的梯度接近 0,学不动',
    '',
    '除 √d_k 把 scores 压回标准正态范围,让 softmax 输出平滑可学。',
),

md(
    '### 2.5 多头 + FFN + 残差 + LayerNorm(v0.2 击穿 Bigram)',
    '',
    'v0.2 一次性加了 4 个东西:',
    '',
    '1. **多头**:n_embed=128 切成 4 个头,每头 32 维。每个头学一种不同的"看上文方式"(押韵 / 对仗 / 意境...)。一头比四头是单点失败,4 头并联鲁棒得多',
    '',
    '2. **FFN**:每个位置过一个 `Linear(C, 4C) → GELU → Linear(4C, C)`。中间扩展 4 倍是经验值。**attention 让位置之间交换信息;FFN 让每个位置内部做非线性加工**',
    '',
    '3. **残差连接** `x = x + sublayer(x)`:让原始输入有一条"直通车"绕过子层。深层网络能训得动的根本原因。改成 `x = sublayer(x)` 会**梯度消失**,深层学不到东西',
    '',
    '4. **LayerNorm**:对每个 token 的 C 维向量做归一化,让数值分布稳定。**我们用 Pre-LN**(`x + Sublayer(LN(x))`),GPT-2 之后的标准做法,比 Post-LN(原 Transformer 论文)更稳定',
    '',
    '一个完整 Block 长这样:',
    '',
    '```python',
    'class Block(nn.Module):',
    '    def forward(self, x):',
    '        x = x + self.attn(self.ln1(x))   # 残差 + Pre-LN + Attention',
    '        x = x + self.ffn(self.ln2(x))    # 残差 + Pre-LN + FFN',
    '        return x',
    '```',
),

md(
    '### 2.6 多层堆叠 + 权重初始化(v0.3 的关键细节)',
    '',
    '把上面的 Block 堆 6 层就是 v0.3。但**直接堆深会训不动** —— 必须加 GPT-2 风格的初始化:',
    '',
    '```python',
    'def _init_weights(module):',
    '    if isinstance(module, nn.Linear):',
    '        nn.init.normal_(module.weight, mean=0.0, std=0.02)',
    '        if module.bias is not None:',
    '            nn.init.zeros_(module.bias)',
    '    elif isinstance(module, nn.Embedding):',
    '        nn.init.normal_(module.weight, mean=0.0, std=0.02)',
    '',
    'self.apply(_init_weights)',
    '```',
    '',
    '**为什么需要**?PyTorch 默认初始化(Kaiming)是为单层 CNN 设计的。6 层叠起来后,每层方差会累积放大或缩小,初始 forward 时数值就跑偏了 —— 6 层后 logits 范围可能爆到 1e3 或缩到 1e-3,loss 完全乱。',
    '',
    'std=0.02 是 GPT-2 实验出来的"适合深层 Transformer"的方差。**判断是否合理的信号**:初始 loss 应该接近 `log(vocab_size)`(纯随机猜测的理论值)。v0.3 初始 loss 应该在 **9.16** 附近(`log(9563) ≈ 9.17`),偏离太多说明初始化没生效。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `model/bigram.py` | 40 | Bigram baseline |',
    '| `model/minigpt_v01.py` | 80 | 单头 `SingleHead` + `MiniGPTv01`(自包含教学版) |',
    '| `model/layers.py` | 75 | 共享:`MultiHeadAttention` / `FeedForward` / `Block` |',
    '| `model/minigpt_v02.py` | 60 | 单 Block 版本,用 `layers.Block` |',
    '| `model/minigpt_v03.py` | 80 | n 层 stack + GPT-2 初始化 —— **后续 Week 5/6/7/8 都用它** |',
    '| `train/train_bigram.py` | 35 | 训练 Bigram |',
    '| `train/train_v01.py` 至 `train_v03.py` | 各 ~40 | 对应 4 个版本的训练入口 |',
    '| `train/utils.py` | 90 | `get_batch / estimate_loss / train_loop` |',
    '| `inference/generate.py` | 60 | CLI 生成,支持所有 4 个 baseline |',
),

md(
    '## 4. 动手做',
    '',
    '按顺序跑 4 个训练,**每跑完一个对一下 val loss**,差距太大就回去找原因。',
),

code(
    'import subprocess',
    '',
    'subprocess.run(["python", "../train/train_bigram.py"], check=True)',
    '# 预期: val loss 收敛到 ~5.43,用时 ~30 秒(T4)',
),

code(
    'subprocess.run(["python", "../train/train_v01.py"], check=True)',
    '# 预期: val loss 6.03 左右,比 Bigram 差! ~1 分钟',
    '# 故意的失败案例,看到这个数字就对了',
),

code(
    'subprocess.run(["python", "../train/train_v02.py"], check=True)',
    '# 预期: val loss ~5.10,击穿 Bigram baseline,~2 分钟',
),

code(
    'subprocess.run(["python", "../train/train_v03.py"], check=True)',
    '# 预期: val loss ~4.14,本周最终模型,~5 分钟',
),

code(
    '# 让 v0.3 写一首诗',
    'subprocess.run(["python", "../inference/generate.py",',
    '                "--model", "v03", "--start", "月", "--tokens", "150"], check=True)',
),

md(
    '## 5. 自测题',
    '',
    '本周的自测题在独立文件里:**`courses/week2_self_test.md`** 共 8 大类 30 道,题目+答案都有。建议:',
    '',
    '1. 先盖住答案,扫一遍题目',
    '2. 心里给每题打分:清楚 / 大概懂 / 完全没思路',
    '3. 把"完全没思路"的回去看对应小节',
    '',
    '**不要直接看答案**。教育心理学叫 "desirable difficulty" —— 大脑只有在尝试调用并失败时,才会真正记住新输入的信息。',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:Bigram 的"虚高参数量"**',
    '',
    'Bigram 91M 参数看着唬人,但都是死记的查找表,毫无泛化能力。**参数量 ≠ 能力**,看 val loss 才数。',
    '',
    '**坑 2:v0.1 单头 16 维的容量瓶颈**',
    '',
    '如果你把 v0.1 的 head_size 改到 64 甚至 128,val loss 会比 Bigram 好(Karpathy 的 nanoGPT 就用了 64)。我们故意用 16 是为了制造对比。',
    '',
    '**坑 3:v0.3 没加 `_init_weights` → loss 不收敛 / 收敛慢**',
    '',
    'index.ipynb 早期版本的 v0.3 就因为没初始化导致深层学不动。修复后 val 才能下到 4.14。',
    '',
    '**坑 4:`generate()` 忘了切 `eval()` → 输出含 Dropout 噪声**',
    '',
    '推理时如果还开着 Dropout,采样会变得很随机(实际效果像温度被偷偷调高)。我们的 `generate()` 都显式 `self.eval()` / `self.train()`,**不要去掉**。',
    '',
    '**坑 5:`generate` 不截 `idx[:, -self.block_size:]` → 上下文超 128 崩**',
    '',
    '`position_embedding` 只学了 0~127 这 128 个位置。超过会 `IndexError` 或拿到错误位置向量。我们的实现都加了截断,你自己改的时候别忘。',
),

md(
    '## 7. 进入 Week 3 前',
    '',
    '现在你应该:',
    '- ☑ 4 个 train_*.py 都跑过,看到 val loss 的下降阶梯',
    '- ☑ 能不看代码画出 Q/K/V → scores → mask → softmax → V 的数据流图',
    '- ☑ 能解释为什么 v0.1 比 Bigram 还差',
    '- ☑ 能解释 Pre-LN vs Post-LN 的区别',
    '',
    'Week 3 我们结构基本不变,但要给训练循环加 4 样东西(LR schedule / AMP / grad clip / weight decay),让训练变得"工业级健康"。',
),

]

save('02_transformer_basics.ipynb', W2)


# ============================================================
# Week 3 · 训练工程化(LR / AMP / Grad Clip / Weight Decay)
# ============================================================
W3 = [

md(
    '# Week 3 · 训练工程化',
    '',
    '> **本周一句话**:模型结构一字不改,给训练循环加 4 样东西(LR 调度 / AMP / 梯度裁剪 / weight decay),让训练从"能跑"变成"健康"。',
    '',
    '上周 v0.3 用恒定 `lr=3e-4` 莽训能到 val 4.14,本周把训练循环升级到 GPT-2 同款配置 —— val 数字不会显著降(因为模型结构没变),但训练稳定性、显存占用、对超参的容忍度全面提升,**为 Week 5 25M 模型打基础**。',
),

md(
    '## 0. 本周目标',
    '',
    '| 版本 | 新增 | 参数量 | val loss | 训练速度 | 备注 |',
    '|---|---|---|---|---|---|',
    '| v0.3(上周) | — | 6.37M | 4.14 | 1× | 恒定 lr,fp32 |',
    '| v0.4 | + warmup + cosine LR | 6.37M | 4.21~4.24 | 1× | 训练曲线更平滑 |',
    '| v0.5 | + AMP + grad clip + wd | 6.37M | 类似 v0.4 | **1.8×** | 显存省一半 |',
    '',
    '看数字像没提升 —— 但你升了 4 项工程化能力,**Week 5 没有它们就训不动 25M**。',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 2 跑完(v0.3 val 4.14 见过)',
    '- 知道什么是"梯度爆炸 / 消失"',
    '',
    '**这周第一次遇到**:',
    '- 学习率调度器 (`get_lr(step)`)',
    '- 自动混合精度 (`torch.amp.autocast` + `GradScaler`)',
    '- 梯度裁剪 (`clip_grad_norm_`)',
    '- AdamW 的 `weight_decay` 和 `betas=(0.9, 0.95)`',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 Warmup + Cosine Decay',
    '',
    '恒定 lr 的问题:训练初期权重还是随机的,大 lr 会把权重打飞;训练后期接近收敛,大 lr 又会让模型在最优点附近震荡。',
    '',
    '**正确做法**:两阶段调度。',
    '',
    '```',
    ' lr',
    '  ↑',
    '  │     ╱──╲___              ← cosine decay 平滑降到 min_lr',
    '  │    ╱     ╲___',
    '  │   ╱          ╲___',
    '  │  ╱               ╲___',
    '  │ ╱                    ╲___',
    '  │╱                          ╲',
    '  ├──┼──────────────────────────→ step',
    '  0 warmup_steps           total',
    '     (200)               (8000)',
    '```',
    '',
    '- **阶段 1 warmup**(前 200 步):lr 从 0 线性升到 max_lr=3e-4',
    '- **阶段 2 cosine**(其余):按 cosine 曲线平滑降到 min_lr=3e-5',
    '',
    'warmup 让模型"暖身",cosine 让后期"收手"。GPT-2/GPT-3/Llama 都这么做。',
),

code(
    '# 完整调度函数(对应 train/lr_schedule.py)',
    'import math',
    '',
    'def warmup_cosine(step, warmup, total, max_lr, min_lr):',
    '    if step < warmup:',
    '        return max_lr * (step + 1) / warmup',
    '    progress = (step - warmup) / max(total - warmup, 1)',
    '    progress = min(progress, 1.0)',
    '    coeff = 0.5 * (1.0 + math.cos(math.pi * progress))',
    '    return min_lr + coeff * (max_lr - min_lr)',
    '',
    '# 打印几个关键点确认形状',
    'warmup, total = 200, 8000',
    'mx, mn = 3e-4, 3e-5',
    'for s in [0, 100, 200, 500, 2000, 4000, 6000, 7999]:',
    '    print(f"  step {s:5d}: lr = {warmup_cosine(s, warmup, total, mx, mn):.6f}")',
),

md(
    '### 2.2 AMP(自动混合精度)',
    '',
    '默认 PyTorch 用 fp32(32 位浮点)。AMP 让 forward / backward 用 **fp16(16 位)**,权重和优化器状态仍用 fp32 保留精度。',
    '',
    '**好处**:',
    '- 显存占用约减半(activation 是显存大头,fp16 占一半)',
    '- T4 / A100 上 fp16 矩阵乘 1.5-3× 快',
    '- **几乎不损失精度**(关键操作仍是 fp32)',
    '',
    '**两个工具**:',
    '',
    '```python',
    'with autocast(device_type="cuda", dtype=torch.float16):',
    '    logits, loss = model(x, y)        # forward 在 fp16',
    '',
    'scaler.scale(loss).backward()          # 反向前把 loss 放大,防止小梯度变 0',
    'scaler.unscale_(optimizer)             # 真正更新前缩回正常尺度',
    'torch.nn.utils.clip_grad_norm_(...)    # ← 必须在 unscale_ 之后!',
    'scaler.step(optimizer)                 # 把 fp16 梯度合并到 fp32 主权重',
    'scaler.update()                        # 动态调整下次的 scale 大小',
    '```',
    '',
    '**核心机制**:fp16 表示范围小,梯度数值经常下溢成 0。`GradScaler` 先把 loss 乘一个大数(scale)放大梯度,反向后再缩回去 —— 让原本会变 0 的小梯度保留下来。',
),

md(
    '### 2.3 梯度裁剪(Grad Clip)',
    '',
    '深层 Transformer 偶尔会出现单步梯度爆炸(比如某个 batch 数值特别极端),一步把训练打飞,后面 loss 再也下不来。',
    '',
    '**修复**(一行):',
    '',
    '```python',
    'torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)',
    '```',
    '',
    '计算所有梯度的 L2 范数,如果超过 1.0 就按比例缩回 1.0。**梯度方向不变,只是步长被砍到安全范围**。',
    '',
    '`max_norm=1.0` 是 LLM 训练的标准值,GPT-2/3/Llama 都这么用。',
    '',
    '**和 AMP 配合的顺序很重要**:',
    '',
    '```python',
    'scaler.scale(loss).backward()      # 梯度此时还是被 scale 放大过的',
    'scaler.unscale_(optimizer)         # 缩回正常尺度',
    'clip_grad_norm_(...)               # 这里 clip 才有意义',
    'scaler.step(optimizer)',
    '```',
    '',
    '顺序错了 → clip 在 scale 后的尺度上做,等于没 clip。',
),

md(
    '### 2.4 AdamW 的 weight_decay 和 betas',
    '',
    '上周 v0.3 我们直接用 `torch.optim.AdamW(model.parameters(), lr=3e-4)`,默认 `weight_decay=0.01`、`betas=(0.9, 0.999)`。',
    '',
    '本周改成 GPT 同款:',
    '',
    '```python',
    'optimizer = torch.optim.AdamW(',
    '    model.parameters(),',
    '    lr=max_lr,',
    '    weight_decay=0.1,        # ← 从 0.01 调到 0.1,L2 惩罚更强',
    '    betas=(0.9, 0.95),       # ← 第二个 beta 从 0.999 → 0.95',
    ')',
    '```',
    '',
    '**weight_decay=0.1 的逻辑**:在每步更新时,把权重往 0 拉一点(`w ← w - lr * 0.1 * w`)。强一点的 wd 防过拟合,LLM 上 0.1 是经验值。',
    '',
    '**betas=(0.9, 0.95) 的逻辑**:`betas[1]` 控制对历史梯度二阶矩(方差)的平滑。默认 0.999 在大 batch / 长训练时太平滑,模型对最近梯度反应慢。GPT-2 / Llama 都用 0.95,反应快一点。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `train/lr_schedule.py` | 30 | `warmup_cosine(step, ...)` + `apply_lr(optimizer, lr)` |',
    '| `train/train_v04.py` | 75 | v0.3 结构 + LR schedule |',
    '| `train/train_v05.py` | 95 | v0.4 + AMP + grad clip + weight_decay |',
    '| `configs/config.py:TrainV05Cfg` | 8 | 8000 / 200 / 3e-4 / 3e-5 / 0.1 / 1.0 |',
    '',
    'v04 → v05 的 diff 主要在 train 循环中间几行;模型类是同一个。',
),

md(
    '## 4. 动手做',
),

code(
    '# 先看一下 lr schedule 是什么形状',
    'import subprocess',
    'subprocess.run(["python", "../train/lr_schedule.py"], check=True)',
),

code(
    '# v0.4: 加 LR schedule',
    'subprocess.run(["python", "../train/train_v04.py"], check=True)',
    '# 预期: val 4.21 ~ 4.24(数字未必比 v0.3 低,但训练曲线更平滑)',
    '# ~8 分钟(T4)',
),

code(
    '# v0.5: 加 AMP + grad clip + weight decay',
    'subprocess.run(["python", "../train/train_v05.py"], check=True)',
    '# 预期: val 接近 v0.4,但训练快 ~1.8× ,显存少 ~40%',
    '# ~6 分钟(T4)',
),

md(
    '**看什么数字判断成功**:',
    '- v0.4 的 lr 字段每步都不一样(warmup 阶段从 0 线性涨),v0.3 一直 3e-4',
    '- v0.5 比 v0.4 实际墙钟时间快(同样 8000 步,少 1-2 分钟)',
    '- v0.5 训练时 `nvidia-smi` 看显存,比 v0.4 低',
),

md(
    '## 5. 自测题',
    '',
    '**A. LR Schedule**',
    '- A1 不加 warmup 直接从 max_lr=3e-4 开始会怎样?用 v0.3 实验过的数据告诉你答案',
    '- A2 cosine decay 把 lr 降到 min_lr 而不是 0,为什么不直接降到 0?',
    '- A3 8000 步训练,warmup 200 步占总训练的 2.5%,这个比例是怎么定的?换成 1000 步会有什么影响?',
    '',
    '**B. AMP**',
    '- B1 如果某个梯度的真实值是 1e-8,fp16 能表示吗?GradScaler 怎么帮它存活?',
    '- B2 forward 用 fp16、权重用 fp32 —— 这两份权重是什么时候同步的?',
    '- B3 T4 / A100 / 消费级 RTX 哪些 GPU 对 fp16 矩阵乘有硬件加速?为什么 V100 之前的卡用 AMP 收益小?',
    '',
    '**C. Grad Clip**',
    '- C1 max_norm=1.0 太严会怎样?太松(比如 100)会怎样?',
    '- C2 为什么用 L2 范数而不是按每个参数单独裁剪?(也就是 clip_grad_value vs clip_grad_norm)',
    '- C3 如果某一步 clip 把梯度缩了 100×,要不要担心?要看哪个指标判断这是常态还是异常?',
    '',
    '**D. Weight Decay**',
    '- D1 AdamW 的 W = decoupled weight decay,和"在 loss 里加 0.1 * ||w||^2"等价吗?差在哪?',
    '- D2 weight_decay 加到 Linear 的 bias 和 LayerNorm 的 weight 上合理吗?(GPT-2 实际不加这些)',
    '- D3 betas=(0.9, 0.999) vs (0.9, 0.95) 在我们 6.37M 模型上能看出明显差别吗?在 1B 模型上呢?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`clip_grad_norm_` 写在 `scaler.unscale_` 之前**',
    '',
    '梯度还在 scale 后的尺度上,clip 等于没 clip,但 `step` 时又会自动 unscale —— 实际相当于完全没 clip。**症状**:训练偶尔崩飞,loss 突然变 nan。',
    '',
    '**坑 2:`autocast` 套到 `estimate_loss` 外面**',
    '',
    '评估时也要用 fp16(否则 train/val 不同精度对比有偏差)。我们的 `estimate_loss` 内部已经套了 autocast。',
    '',
    '**坑 3:cosine decay 的 total_steps 算错**',
    '',
    'resume 训练时如果 total_steps 没相应延长,模型会在 lr 已经降到 min_lr 之后还硬训 —— 学不动新东西。Week 4 的 resume 会用一个新的小 lr 重启 schedule(不是接着上次的 schedule)。',
    '',
    '**坑 4:AMP 在 CPU 上跑会报错或退化到 fp32**',
    '',
    '`autocast(device_type="cuda", ...)` 显式指定 device_type。如果你在 CPU 上跑这段代码,要么改成 `device_type="cpu"` + bfloat16,要么直接跳过 AMP。',
    '',
    '**坑 5:`GradScaler` 第一步 `inf check` 失败 → 静默不更新**',
    '',
    'GradScaler 会探测梯度是否溢出 → 溢出就跳过这一步并降低 scale。第一次启动 scale 偏高时可能跳过几步,看着像"loss 不降",其实是正常 warmup。**别看到第一步没更新就慌**。',
),

md(
    '## 7. 进入 Week 4 前',
    '',
    '现在你应该:',
    '- ☑ 跑过 train_v04 和 train_v05,看到 lr 不再是常数',
    '- ☑ 能解释 GradScaler 为什么必须存在(不是装饰)',
    '- ☑ 知道 `clip_grad_norm_` 必须在 `unscale_` 之后',
    '- ☑ 体感到 v0.5 比 v0.4 快、占显存少',
    '',
    'Week 4 我们做完整训练工程闭环:checkpoint 系统 + 断点续训 + TensorBoard 监控。把"实验室代码"升级成"工业代码"。',
),

]

save('03_optim_engineering.ipynb', W3)


# ============================================================
# Week 4 · Checkpoint + Resume + TensorBoard
# ============================================================
W4 = [

md(
    '# Week 4 · Checkpoint + Resume + TensorBoard',
    '',
    '> **本周一句话**:训练随时能断、断了能续、断之前的曲线能看 —— 把训练代码从"实验室一次性"变成"工程闭环"。',
    '',
    '本周不会有新的 val loss 突破。但学完之后,你的 v0.7 就可以放心训 8 小时 + 中间断电 + 重启续训 + 在浏览器看实时曲线。**为 Week 5 25M 大模型做完整准备**。',
),

md(
    '## 0. 本周目标',
    '',
    '| 版本 | 新增 | val | 工程能力 |',
    '|---|---|---|---|',
    '| v0.5(上周) | AMP + clip + wd | 4.21 | 训完只剩 model.state_dict() |',
    '| v0.6 | + 完整 checkpoint | 4.21 | best.pt + latest.pt,可恢复全部状态 |',
    '| v0.7 | + Resume + TensorBoard | 4.21 | 续训不重头,实时监控 |',
    '',
    '关键产出:',
    '- `checkpoints/v06/{best,latest}.pt` —— 完整训练状态打包',
    '- `tb_logs/v07_*/` —— TensorBoard event 文件',
    '- 可以 `python train/train_v07.py --resume` 续训',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 3 跑完(知道 AMP / GradScaler 怎么用)',
    '- 知道 `torch.save / torch.load`',
    '',
    '**这周第一次遇到**:',
    '- `state_dict()` 包含什么(model / optimizer / scaler 各自的)',
    '- `weights_only=True/False`(PyTorch 2.4+ 的安全机制)',
    '- TensorBoard `SummaryWriter`、`add_scalar`',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 一个完整的 checkpoint 要存什么',
    '',
    '只存 `model.state_dict()` 是**不够的**。完整 checkpoint 需要:',
    '',
    '```python',
    '{',
    '    "step":             3500,                  # 走到第几步',
    '    "model_state":      model.state_dict(),    # 模型权重',
    '    "optimizer_state":  optimizer.state_dict(),# Adam 的 m / v 动量',
    '    "scaler_state":     scaler.state_dict(),   # AMP scale 当前值',
    '    "best_val":         4.21,                  # 历史最佳,resume 后接着比',
    '    "config":           {n_embed: 192, ...},   # 模型结构,重建用',
    '}',
    '```',
    '',
    '**为什么 optimizer 必须存**?Adam 维护着每个参数的两个动量(`m` 一阶、`v` 二阶)。这些动量本身就是训练历史的"记忆" —— 不存的话 resume 等于从头初始化 optimizer,前 500 步训练全废。',
    '',
    '**为什么 config 要存**?推理 / 评测时要重建模型,如果忘了当时用的 `n_embed=192` 还是 384,载入权重时会 shape mismatch。',
),

md(
    '### 2.2 best.pt vs latest.pt 的双轨保存',
    '',
    '```',
    '       ┌─────────────────────┐',
    '       │  best.pt            │  ← 每次 val 创新低就覆盖',
    '       │  (推理 / 评测用)   │',
    '       └─────────────────────┘',
    '',
    '       ┌─────────────────────┐',
    '       │  latest.pt          │  ← 每 1000 步覆盖一次',
    '       │  (resume 续训用)   │',
    '       └─────────────────────┘',
    '```',
    '',
    '为什么要两个?',
    '- **best**:跑评测、生成、Week 5 之后做 fine-tune 起点 —— 要"模型最好的瞬间"',
    '- **latest**:断点续训 —— 要"最近的瞬间",哪怕 val 当时刚好在波动期',
    '',
    '一个文件兼顾两用 → 你要不要用 best 又开始训(把最佳状态训坏),要不要用最近又拿不到最佳 —— 两难。**用两个文件,问题消失**。',
),

md(
    '### 2.3 Resume 时 LR Schedule 怎么对齐',
    '',
    '上周 v0.4/v0.5 的 LR schedule 是按 `step` 索引的:',
    '',
    '```python',
    'lr = warmup_cosine(step, warmup=200, total=8000, ...)',
    '```',
    '',
    '如果从 step 3500 续训到 8000(只剩 4500 步),硬接 schedule 会很尴尬:warmup 早过了,cosine 也已经降到一半 —— 续训这段几乎用最小 lr,基本学不到东西。',
    '',
    '**我们的做法**(`train_v07.py --resume`):',
    '',
    '- 重新定义一个**小 schedule**:max_lr=1e-4(原 3e-4 的 1/3)、warmup=100、total=4000',
    '- 让续训阶段有自己的"暖身 + 衰减"',
    '- 全局 `step` 继续递增(`start_step + local_step`),用于 TensorBoard 横轴和保存',
    '',
    '本质思想:**resume = 在已有权重基础上开一段新训练**,不是机械接续。',
),

md(
    '### 2.4 TensorBoard 监控什么有用',
    '',
    '不要无脑写所有东西。写少而精的指标:',
    '',
    '| 指标 | 写入频率 | 看什么 |',
    '|---|---|---|',
    '| `lr` | 每步 | 确认 schedule 形状对 |',
    '| `train/loss_step` | 每步 | 单步噪声大,但能看到瞬时尖刺 |',
    '| `grad_norm` | 每步 | **诊断利器** —— 突然飙升 = 数据/初始化有问题 |',
    '| `train/loss_eval` | 每 eval_interval | 平滑曲线,看趋势 |',
    '| `val/loss` | 每 eval_interval | 关键指标 |',
    '',
    '看 `grad_norm` 比看 loss 更早发现问题 —— loss 还没爆的时候 grad_norm 已经飙到 10+。我们的 v0.7 把 `grad_norm` 当一等公民。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `train/checkpoint.py` | 50 | `save_checkpoint` / `load_checkpoint`,接口干净 |',
    '| `train/train_v06.py` | 130 | v0.5 + 双轨 checkpoint |',
    '| `train/train_v07.py` | 165 | v0.6 + `--resume` + TensorBoard |',
    '',
    '`checkpoint.py` 是工具库,被 v06 / v07 / Week 5 v08 / Week 6 SFT / Week 7 DPO **复用**。一个干净的小工具能消除很多重复代码。',
),

md(
    '## 4. 动手做',
),

code(
    'import subprocess',
    '',
    '# v0.6: 训练 + 保存 best/latest',
    'subprocess.run(["python", "../train/train_v06.py"], check=True)',
    '# 预期: best.pt 和 latest.pt 各约 80 MB(模型 + 优化器状态)',
),

code(
    'import os',
    'ckpt_dir = "../checkpoints/v06"',
    'for fn in os.listdir(ckpt_dir):',
    '    size = os.path.getsize(f"{ckpt_dir}/{fn}") / 1e6',
    '    print(f"  {fn}: {size:.2f} MB")',
),

code(
    '# v0.7: 从零训(带 TensorBoard)',
    'subprocess.run(["python", "../train/train_v07.py"], check=True)',
    '# tb_logs/v07_fresh_*/ 下会有 event 文件',
),

code(
    '# v0.7: 续训测试(从 v0.6 的 latest 接着训 4000 步)',
    'subprocess.run(["python", "../train/train_v07.py", "--resume"], check=True)',
    '# 预期: 一开始 val loss 接近 4.21(说明 resume 成功),',
    '#       而不是 9.2(说明 model_state 没加载上)',
),

md(
    '**启动 TensorBoard**:',
    '',
    '```powershell',
    'tensorboard --logdir tb_logs',
    '```',
    '',
    '浏览器开 http://localhost:6006,选 `v07_*` 的几个 run 对比。**会看到**:',
    '- `lr` 是 warmup + cosine 的标准形状',
    '- `train/loss_step` 抖动很大(单步噪声),但整体下行',
    '- `train/loss_eval` 是平滑曲线(20 个 batch 平均)',
    '- `val/loss` 平滑下降',
    '- `grad_norm` 一般在 0.3~2 之间,偶尔尖刺到 5+,被 clip 救回',
),

md(
    '## 5. 自测题',
    '',
    '**A. Checkpoint**',
    '- A1 如果只存 `model.state_dict()` 续训,前 1000 步会和正常训练有什么差别?为什么?',
    '- A2 `latest.pt` 每 1000 步覆盖一次,如果在第 999 步崩了,丢了多少?如果改成每 100 步覆盖,代价是什么?',
    '- A3 `weights_only=True`(默认)和 `weights_only=False` 各有什么风险?为什么我们的 `load_checkpoint` 用 `False`?',
    '',
    '**B. Resume**',
    '- B1 resume 时如果用原 schedule(max_lr=3e-4 / warmup=200 / total=8000)继续,从 step 3500 跑到 8000,会发生什么?',
    '- B2 我们的 resume 用 max_lr=1e-4 比原 3e-4 小 3 倍,这个比例怎么定的?如果还用 3e-4 会怎样?',
    '- B3 如果训练时 model 结构变了(比如加了一层),还能 `load_state_dict` 吗?',
    '',
    '**C. TensorBoard**',
    '- C1 为什么 `train/loss_step` 抖动很大,`train/loss_eval` 却很平滑?',
    '- C2 `grad_norm` 突然飙到 10+,但 loss 还没崩 —— 你会怎么处理?',
    '- C3 多次 resume 同一 ckpt 会在 TB 里产生多条线吗?怎么对比?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`torch.load(weights_only=True)` 加载完整 ckpt 会失败**',
    '',
    'PyTorch 2.4+ 默认 `weights_only=True`,只接受纯权重(`Tensor`),拒绝完整 dict + Python 对象。我们的 ckpt 含 config dict,必须 `weights_only=False`。',
    '',
    '**坑 2:resume 前忘了重建 optimizer / scaler**',
    '',
    '```python',
    '# 错',
    'optimizer = ...  # 已经存在',
    'optimizer.load_state_dict(ckpt["optimizer_state"])   # 报错: param shape mismatch',
    '',
    '# 对',
    'model = MyModel(**config); model.to(device)',
    'optimizer = AdamW(model.parameters(), ...)            # ← 必须用新模型的 parameters',
    'optimizer.load_state_dict(ckpt["optimizer_state"])',
    '```',
    '',
    'optimizer 状态和 model.parameters() 一一对应,顺序不能错。',
    '',
    '**坑 3:多个 run 写到同一 TB 目录 → 曲线混在一起**',
    '',
    '我们用 `f"v07_{tag}_{datetime.now().strftime(...)}"` 给每个 run 唯一目录。同名会被 TB 当作同一个 run 续写,曲线乱跳。',
    '',
    '**坑 4:resume 后 TB 横轴从 0 重新开始**',
    '',
    '我们传给 `add_scalar` 的是 `global_step = start_step + local_step`,不是 local_step。横轴连续才能看到完整曲线。',
    '',
    '**坑 5:checkpoint 越存越多撑爆磁盘**',
    '',
    'Week 5 v08 / Week 6 SFT 的 checkpoint 各 ~100 MB,跑几个版本就吃 GB。HuggingFace trainer 有 `save_total_limit`,我们的 `train_loop` 没有 —— 自己定期 `rm` 老的。',
),

md(
    '## 7. 进入 Week 5 前',
    '',
    '现在你应该:',
    '- ☑ `checkpoints/v06/{best,latest}.pt` 都存在,各 ~80 MB',
    '- ☑ 跑过 `--resume`,看到续训从 4.21 附近开始(不是 9.2)',
    '- ☑ TensorBoard 里能看到 lr / loss / grad_norm 三条核心曲线',
    '- ☑ 能解释 best vs latest 为什么必须分开',
    '',
    'Week 5 数据规模 ×5、模型规模 ×4 —— 唐+宋诗+宋词,25M 参数。**没有 Week 4 的工程能力,Week 5 训不完**(中间一次电脑断电就全废)。',
),

]

save('04_checkpoint_resume.ipynb', W4)


if __name__ == '__main__':
    print('Week 1-4 课程文件生成完毕')
