"""生成 Week 5-8 的课程 .ipynb。"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _course_helpers import code, md, save


# ============================================================
# Week 5 · 扩规模 + 加宋诗宋词
# ============================================================
W5 = [

md(
    '# Week 5 · 扩规模 + 加宋诗宋词',
    '',
    '> **本周一句话**:数据从 4M → 22M 字符,模型从 6.37M → 25M 参数,vocab 从 9k → 14k —— val loss 跌到 4.03,生成开始出现真正的"金句"。',
    '',
    '这是**数据 + 模型双管齐下**的一周。单独扩任意一个收益都有限,两个一起上才有质变。',
),

md(
    '## 0. 本周目标',
    '',
    '| 维度 | v0.7 (上周) | v0.8 (本周) | 倍数 |',
    '|---|---|---|---|',
    '| 数据字符数 | 4 M(仅唐诗) | 22 M(唐+宋诗+宋词) | 5.5× |',
    '| vocab_size | 9,563 | ~14,500 | 1.5× |',
    '| n_embed | 192 | 384 | 2× |',
    '| n_layer | 6 | 8 | 1.3× |',
    '| block_size | 128 | 256 | 2× |',
    '| 参数量 | 6.37 M | ~25 M | 3.9× |',
    '| val loss | 4.21 | **~4.03** | -0.18 |',
    '| 生成质量 | 押韵、句式 | + 用词典雅、意境连贯 | 质变 |',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 4 跑完(checkpoint 工程通了)',
    '- 知道 GPU 显存怎么算(`参数 + 优化器状态 + activation`)',
    '',
    '**这周第一次遇到**:',
    '- 多数据源合并 + 打乱(为什么必须打乱)',
    '- vocab 扩展的兼容性',
    '- 大模型上 batch_size 的取舍',
    '- `.clone()` 切断 view 共享(否则 .pt 文件翻倍)',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 为什么宋诗 + 宋词必须打乱',
    '',
    '`prepare_v2.py` 的关键一行:',
    '',
    '```python',
    'random.seed(42)',
    'random.shuffle(poems)        # ← 这行!',
    '```',
    '',
    '如果不打乱,数据顺序是:',
    '',
    '```',
    '  [唐诗 5w 首] → [宋诗 26w 首] → [宋词 2w 首]',
    '```',
    '',
    '90/10 切分之后,**验证集前 90% 是宋词、后 10% 是宋词 + 末尾的少量** —— 模型完全没在唐诗 / 宋诗上被验证过。val loss 会变得"看上去很好"但不真实。',
    '',
    '打乱之后,train 和 val 都是三种来源混合采样,验证才有意义。',
    '',
    '**通用原则**:多源数据 → 必须打乱再切。这个 bug 在大规模训练里很常见且很隐蔽。',
),

code(
    '# 演示打乱前后验证集的"成分差异"',
    'import random',
    '',
    'poems = ["[T]"] * 5000 + ["[S诗]"] * 26000 + ["[S词]"] * 2000',
    '',
    'def val_composition(p):',
    '    n = int(0.95 * len(p))',
    '    val = p[n:]',
    '    return {x: val.count(x) for x in set(val)}',
    '',
    'print("打乱前 val:", val_composition(poems))',
    'random.seed(42); random.shuffle(poems)',
    'print("打乱后 val:", val_composition(poems))',
),

md(
    '### 2.2 vocab 扩展的兼容性问题',
    '',
    '宋诗宋词带来一些唐诗里没有的字(冷僻字、词牌专用字)。重新统计后 vocab 从 9563 涨到 ~14500。',
    '',
    '**关键决策**:tokenizer_v1 和 tokenizer_v2 是**完全独立**的两个文件,**ID 编号不兼容**。',
    '',
    '```',
    'v1: stoi["月"] = 4287',
    'v2: stoi["月"] = 6512    # ← 重排了',
    '```',
    '',
    '所以 v0.8 不能直接 load v0.7 的权重 —— embedding 的"行号意义"对不上。Week 5 干脆**从头训** v0.8,放弃 v0.7 的权重(数据和模型都变了,迁移成本不如重训)。',
    '',
    '**Week 6 SFT 时**,vocab 只加了 5 个特殊 token(append 到末尾),旧 ID 不动,这时候才有"权重迁移"的可能。',
),

md(
    '### 2.3 大模型的显存账',
    '',
    '25M 模型 + AMP + block_size=256 + batch_size=32 在 T4(15.6 GB)能不能跑?粗算:',
    '',
    '| 项目 | 估算公式 | 数值 |',
    '|---|---|---|',
    '| 模型 fp16 权重 | 25M × 2 bytes | 50 MB |',
    '| 模型 fp32 master | 25M × 4 bytes | 100 MB |',
    '| AdamW m + v 状态 | 25M × 2 × 4 bytes | 200 MB |',
    '| Activation(主要)| `B × T × C × n_layer × ~5` | 32 × 256 × 384 × 8 × 5 ≈ 130 MB |',
    '| Attention scores | `B × n_head × T²` | 32 × 6 × 256² ≈ 12 MB |',
    '| **总计** | | **~500 MB** |',
    '',
    'T4 富富有余。但 batch_size 调到 64 + block_size 调到 512 就接近上限了。',
    '',
    '**实际 monitor**:训练前 `nvidia-smi` 看 baseline,训练第 100 步再看,差值就是占用。',
),

md(
    '### 2.4 .clone() 切断 view 共享',
    '',
    '一个隐蔽的内存陷阱:',
    '',
    '```python',
    'data = torch.tensor(...)           # 22 MB',
    'train = data[:int(0.95*len(data))]    # view,共享 storage',
    'val   = data[int(0.95*len(data)):]    # view,共享 storage',
    '',
    'torch.save(train, "train.pt")      # ← 实际写入 22 MB(整个 storage),不是 21 MB!',
    'torch.save(val,   "val.pt")        # ← 又写入 22 MB!',
    '```',
    '',
    '`torch.save` 看到的是底层 storage,view 共享同一份 storage 就各自序列化整份 → 文件大小翻倍。',
    '',
    '**修复**:存之前 `.clone()`,创建独立 storage:',
    '',
    '```python',
    'train = data[:n].clone()',
    'val   = data[n:].clone()',
    'torch.save(train, ...)             # 现在只写 21 MB',
    'torch.save(val,   ...)             # 只写 1 MB',
    '```',
    '',
    '`prepare_v2.py` 里就加了这一行,**别去掉**。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `data/prepare_v2.py` | 100 | 唐+宋诗+宋词合并,打乱,清洗,建 v2 tokenizer,切分 |',
    '| `configs/config.py:MiniGPTv08Cfg` | 6 | n_embed=384, n_head=6, n_layer=8, block_size=256 |',
    '| `configs/config.py:TrainV08Cfg` | 9 | num_steps=10000, batch=32, max_lr=3e-4 |',
    '| `train/train_v08.py` | 165 | 用现有 `MiniGPTv03` 类 + v2 数据 + 全套工程化 |',
    '',
    '**注意**:v0.8 没有新的 model 类,**直接复用 v0.3 的 `MiniGPTv03`,只改超参**。架构演进到 v0.3 就已经定型了,后面 5/6/7 都靠它。这是好的设计:模型类不变,通过 config 切尺寸。',
),

md(
    '## 4. 动手做',
),

code(
    '# 先准备 v2 数据(下载宋诗宋词 + 合并 + 清洗 + 编码)',
    '# 注意: chinese-poetry 仓库已经在 Week 1 clone 过,这里只下载新分支',
    'import subprocess',
    'subprocess.run(["python", "../data/prepare_v2.py"], check=True)',
    '# 预期:',
    '#   唐诗: 57603, 宋诗: 286986, 宋词: 19990   (总 ~36 万首)',
    '#   清洗后约 22M 字符',
    '#   vocab_size: ~14500',
    '#   train: ~21M tokens, val: ~1M tokens',
),

code(
    '# 训练 v0.8 (T4 大约 40 分钟,可以喝杯咖啡)',
    'subprocess.run(["python", "../train/train_v08.py"], check=True)',
    '# 预期: val loss 跌到 ~4.03',
    '# best.pt 和 latest.pt 各约 300 MB(25M 模型 + 优化器 + scaler)',
),

code(
    '# 看一下 v0.8 写诗',
    '# (注意 train_v08 没有专门的 generate 入口,可以借用 generate.py 的逻辑)',
    'import torch, pickle',
    'import sys, pathlib',
    'sys.path.insert(0, str(pathlib.Path().resolve().parent))',
    'from model.minigpt_v03 import MiniGPTv03',
    'from tokenizer.tokenizer import CharTokenizer',
    'from configs.config import CHECKPOINT_DIR, TOKENIZER_V2_FILE',
    '',
    'device = "cuda" if torch.cuda.is_available() else "cpu"',
    'ckpt = torch.load(CHECKPOINT_DIR / "v08" / "best.pt", map_location=device, weights_only=False)',
    'cfg = ckpt["config"]',
    'model = MiniGPTv03(cfg["vocab_size"], cfg["n_embed"], cfg["n_head"],',
    '                   cfg["n_layer"], cfg["block_size"], cfg["dropout"]).to(device)',
    'model.load_state_dict(ckpt["model_state"])',
    '',
    'tok = CharTokenizer.load(TOKENIZER_V2_FILE)',
    'start = torch.tensor([tok.encode("月")], dtype=torch.long, device=device)',
    'out = model.generate(start, max_new_tokens=200, temperature=0.8)',
    'print(tok.decode(out[0].tolist()))',
),

md(
    '## 5. 自测题',
    '',
    '**A. 数据**',
    '- A1 唐诗 5w + 宋诗 28w + 宋词 2w,为什么宋诗数量最大?如果只想训写"五言绝句",这种分布合适吗?',
    '- A2 不打乱直接切的话,val 会全是哪种?对训练时 val 曲线的判断会有什么误导?',
    '- A3 v2 切 95/5 而不是 v1 的 90/10,理由是什么?',
    '',
    '**B. vocab**',
    '- B1 v1 → v2 vocab 涨了 ~5000 字,但模型参数量没涨那么多 —— 多出来的字主要影响哪几层?',
    '- B2 如果 v0.8 训完之后,某天突然想加 v3 的"明清诗",怎么处理 vocab 兼容?',
    '- B3 字符级 tokenizer 在 vocab 涨到 5w(全字符全标点)时会怎样?',
    '',
    '**C. 模型规模**',
    '- C1 n_embed 从 192 涨到 384,参数量为什么涨了 3.9× 而不是 2×?',
    '- C2 block_size 从 128 涨到 256,attention 计算量涨了多少倍?',
    '- C3 25M 模型在 T4 上 batch_size 极限大概是多少?(自己用上面的显存公式估)',
    '',
    '**D. 训练**',
    '- D1 v0.8 训 10000 步,为什么 warmup 从 v0.5 的 200 涨到 500?',
    '- D2 val 4.03 vs v0.7 的 4.21,看着只降了 0.18,生成质量真的会有"质变"吗?为什么?',
    '- D3 如果不重新训,直接用 v0.5 的权重 + v2 数据继续 fine-tune 会怎样?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`tang_poems_clean.txt` 还在,误用了 v1 的清洗后文件**',
    '',
    'v1 和 v2 的清洗后文件分别叫 `tang_poems_clean.txt` 和 `poems_v2_clean.txt`,**别混了**。v2 train 时如果误读 v1 文本,vocab 不一致 → 编码崩。',
    '',
    '**坑 2:25M 模型 + block_size=256,batch_size=64 会 OOM**',
    '',
    'attention scores 是 `B × n_head × T²`,T=256 时一个 batch 32 already 12 MB,翻倍就是 24 MB,反向传播时再 ×3 ~ ×4 (中间 activation)。T4 上 batch=32 安全,64 风险大。',
    '',
    '**坑 3:中途 OOM 之后没清缓存,后续训练莫名其妙慢**',
    '',
    '`torch.cuda.empty_cache()` 不是必须,但 OOM 后建议跑一次。或者干脆 restart kernel。',
    '',
    '**坑 4:`prepare_v2.py` 跑到一半网络断,chinese-poetry clone 失败**',
    '',
    '`data/download.py` 是 idempotent 的(检查到目录存在就跳过)。但如果上次 clone 到一半留下一个空目录或损坏目录,手动 `rm -rf raw/chinese-poetry/` 重来。',
    '',
    '**坑 5:训练 30 分钟之后笔记本休眠 → 训练中断 → 没用 checkpoint 全废**',
    '',
    'Week 4 的 checkpoint 系统就是为这种情况准备的。`train_v08.py` 每 1000 步存 latest,休眠回来后 `python train/train_v07.py --resume` 改成 v08 版续训。',
),

md(
    '## 7. 进入 Week 6 前',
    '',
    '现在你应该:',
    '- ☑ `data/processed/` 下既有 v1 文件又有 v2 文件,大小约 100 MB',
    '- ☑ `checkpoints/v08/best.pt` 存在,~100 MB',
    '- ☑ v0.8 生成的诗用词比 v0.7 明显更典雅,押韵更稳',
    '- ☑ 能解释为什么 v1 → v2 必须重新训而不能 fine-tune',
    '',
    'Week 6 我们要给 v0.8 加"指令能力" —— 不再是"给一个字续写",而是"给我题目 + 风格,你按要求写一首"。需要 SFT(Supervised Fine-Tuning) + 特殊 token + prompt mask。',
),

]

save('05_scale_up_song_poetry.ipynb', W5)


# ============================================================
# Week 6 · SFT 指令微调
# ============================================================
W6 = [

md(
    '# Week 6 · SFT 指令微调',
    '',
    '> **本周一句话**:让模型从"续写"升级到"按指令生成" —— 给它"题目 + 风格"两个槽位,它返回符合要求的诗。',
    '',
    '这是从"语言模型"到"指令模型"的关键一步。技术上需要:特殊 token、prompt mask、vocab 扩展时的权重迁移、小 lr 微调。',
),

md(
    '## 0. 本周目标',
    '',
    '| 维度 | v0.8(预训练) | v0.9(SFT) |',
    '|---|---|---|',
    '| 用法 | `generate("月", 200)` 续写 | `prompt = 题目=春雨 + 风格=五绝` 按指令生成 |',
    '| 数据 | 22M 字符自由文本 | 37k 条结构化 (题目, 风格, 正文) |',
    '| vocab | 14,477 | 14,482(加 5 个特殊 token) |',
    '| lr | 3e-4(预训练) | 5e-5(小 6 倍) |',
    '| val loss | 4.03 | ~3.55(注意 SFT loss << 预训,因为 prompt 被 mask) |',
    '',
    '能跑的 prompt 例子:',
    '- "请以「春雨」为题,写一首五言绝句"',
    '- "请以「程序员」为题,写一首七言绝句"(看老模型对现代题材的反应)',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 5 跑完(v0.8 best 存在)',
    '- 知道什么是"loss mask"',
    '',
    '**这周第一次遇到**:',
    '- 特殊 token(`<|题目|>` 等)的设计与编码',
    '- prompt vs completion 的概念',
    '- `cross_entropy(ignore_index=-100)` 用法',
    '- vocab 扩展时迁移权重的边界条件',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 SFT 数据格式',
    '',
    '每个样本是一段拼接后的文本:',
    '',
    '```',
    '<|题目|>静夜思<|风格|>五言绝句<|开始|>床前明月光，疑是地上霜。举头望明月，低头思故乡。<|结束|>',
    '```',
    '',
    '前半截(`<|题目|>...<|开始|>`)叫 **prompt**,后半截(诗本身 + `<|结束|>`)叫 **completion**。',
    '',
    '**这一段一次性整个塞进模型 forward**,模型在每个位置都要预测下一个 token。但 —— ',
    '',
    '### 2.2 prompt mask:只在 completion 上算 loss',
    '',
    '问题:如果对整段算 loss,模型会努力学"如何续写题目和风格" —— 那是我们给它的输入,本就不该学。',
    '',
    '**修复**:把 prompt 部分的 target 设成 `-100`,`F.cross_entropy(ignore_index=-100)` 自动跳过。',
    '',
    '```python',
    'L = len(ids) - 1',
    'x[i, :L] = torch.tensor(ids[:-1])    # 输入',
    'y[i, :L] = torch.tensor(ids[1:])     # 目标',
    '',
    'start_pos = ids.index(START_ID)       # <|开始|> 的位置',
    'y[i, :start_pos] = -100               # ← prompt 部分 mask 掉',
    '```',
    '',
    '**注意 mask 的索引**:y[i, :start_pos] 而不是 :start_pos+1。因为 y[t] 预测的是 ids[t+1],我们想从 ids[start_pos+1](正文第一个字)开始算 loss,对应 y[start_pos:] 保留。',
),

md(
    '### 2.3 特殊 token 必须接在 vocab 末尾',
    '',
    'v3 tokenizer 的设计:',
    '',
    '```',
    'v2: id  0..14476  (字符 + 标点)',
    'v3: id  0..14476  (完全不动!)',
    '         14477   <|题目|>',
    '         14478   <|风格|>',
    '         14479   <|开始|>',
    '         14480   <|结束|>',
    '         14481   <|pad|>',
    '```',
    '',
    '**为什么必须 append**?Week 6 要把 v0.8 (vocab=14477) 的权重灌进 v0.9 (vocab=14482) —— 只有旧 ID 完全不动,前 14477 行 embedding 才能 1:1 拷贝。如果在中间插入,所有 ID 重排,权重对不上 → 等于从头训练。',
    '',
    '**通用原则**:扩 vocab 永远在尾部加,不在中间插。',
),

md(
    '### 2.4 vocab 扩展的权重迁移',
    '',
    '```python',
    'def transfer_weights_to_larger_vocab(new_model, v08_state, old_vocab=14477):',
    '    new_state = new_model.state_dict()',
    '    for key, val in v08_state.items():',
    '        if key in ("token_embedding.weight", "lm_head.weight"):',
    '            new_state[key][:old_vocab] = val   # 前 14477 行拷贝,后 5 行保留随机初始化',
    '        else:',
    '            new_state[key] = val               # 其他层 shape 不变,直接拷贝',
    '    new_model.load_state_dict(new_state)',
    '```',
    '',
    '**关键 invariant**:旧字的 embedding 行 / lm_head 行 = v0.8 学到的;新 5 行 = 随机初始化,SFT 训练时会被快速学好(因为 `<|题目|>` 等出现频次极高,梯度信号强)。',
    '',
    '**结果**:v0.9 一开始就具备 v0.8 的全部语言能力,只是多了 5 个新词需要学。比从头训 v0.9 快 100×。',
),

md(
    '### 2.5 为什么 SFT lr = 预训练 lr / 6',
    '',
    'v0.8 预训用 max_lr=3e-4;v0.9 SFT 用 5e-5。',
    '',
    '**原因**:',
    '- v0.8 已经训了 10000 步,权重在一个相对好的位置',
    '- 大 lr 会"踢飞"已学到的语言能力,模型只剩下"按指令生成"但不会写诗了 —— 灾难性遗忘',
    '- 小 lr 让模型"在已有能力之上做小修改"',
    '',
    '通用规律:**任何 fine-tune 阶段的 lr 都比预训阶段小 5-10×**。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `data/classify.py` | 35 | 按句数/字数判定 五绝/七绝/五律/七律 |',
    '| `tokenizer/build_v3.py` | 35 | v2 + 5 个特殊 token → v3 |',
    '| `data/prepare_sft.py` | 60 | 用 classify + v3 编码,构造 list[list[int]] |',
    '| `configs/config.py:SFTCfg` | 9 | 3000 步、lr 5e-5、batch 32、max_len 128 |',
    '| `train/train_v09_sft.py` | 165 | vocab 扩展 + 权重迁移 + prompt mask + 训练 |',
    '| `inference/generate_sft.py` | 105 | CLI 生成,带 `--battery` 12 题套件 |',
),

md(
    '## 4. 动手做',
),

code(
    'import subprocess',
    '',
    '# 1. 建 v3 tokenizer(秒级)',
    'subprocess.run(["python", "../tokenizer/build_v3.py"], check=True)',
    '# 预期: old vocab 14477 -> new vocab 14482',
),

code(
    '# 2. 构造 SFT 样本(~30 秒)',
    'subprocess.run(["python", "../data/prepare_sft.py"], check=True)',
    '# 预期: ~37000 条样本,长度中位数 ~50,最长 ~100',
),

code(
    '# 3. SFT 训练(~10 分钟 T4)',
    'subprocess.run(["python", "../train/train_v09_sft.py"], check=True)',
    '# 预期:',
    '#   开始 val ~5-6(刚加了 5 个新 token,新权重还没学好)',
    '#   500 步内降到 ~4',
    '#   3000 步收敛到 ~3.55',
    '#   注意: SFT loss 远低于预训 loss(因为 prompt 部分被 mask)',
),

code(
    '# 4. 写诗',
    'subprocess.run(["python", "../inference/generate_sft.py",',
    '                "--title", "春雨", "--style", "五言绝句"], check=True)',
),

code(
    '# 5. 12 题套件(对照不同难度题目的发挥)',
    'subprocess.run(["python", "../inference/generate_sft.py", "--battery"], check=True)',
    '# 4 档 × 3 题:',
    '#   A 档 古典正统(明月、江雪、饮酒) — 应该最稳',
    '#   B 档 古代少见(观棋、夜读、卖花) — 句式应该 OK',
    '#   C 档 现代题用古意(咖啡、地铁、独居) — 看模型有没有"硬翻"能力',
    '#   D 档 完全现代(程序员、深度学习、996) — 大概率胡来,但很有趣',
),

md(
    '## 5. 自测题',
    '',
    '**A. 数据格式**',
    '- A1 SFT 样本里 `<|结束|>` 必须有吗?不加会怎样?',
    '- A2 题目 + 风格 + 正文的顺序能换吗?换成 风格 + 题目 + 正文 训出来会不同吗?',
    '- A3 我们 max_len=128,SFT 数据平均长度 ~50。剩余 ~78 个位置 pad,这些位置算 loss 吗?',
    '',
    '**B. prompt mask**',
    '- B1 如果不 mask prompt(整段算 loss),模型最终会变成什么样?',
    '- B2 mask 用 `-100` 而不是 `0`,原因?',
    '- B3 我们的 mask 用 `y[i, :start_pos] = -100`,如果改成 `y[i, :start_pos+1] = -100` 会怎样?',
    '',
    '**C. vocab 扩展**',
    '- C1 如果不迁移 v0.8 权重,从头训 v0.9,要训多少步才能达到 val 3.55?(粗估)',
    '- C2 5 个新 token 的 embedding 初始化为 0 vs 随机正态,有什么区别?',
    '- C3 如果旧 ID 顺序变了(比如新加的 token 插在中间),迁移代码会失败还是静默错乱?',
    '',
    '**D. 超参**',
    '- D1 lr 从 5e-5 改成 3e-4(同预训),前 100 步会观察到什么现象?',
    '- D2 SFT 训 3000 步够用吗?训 10000 会怎样?',
    '- D3 batch_size 32 vs 16 在 SFT 阶段哪个更"稳"?为什么?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`stoi["<|题目|>"]` 编不出来 —— 因为传成了 "<|题目|>" 7 个字符**',
    '',
    'special token 必须**整体**当一个 key 去查,我们的 `encode_pieces` 函数会先检测整段是不是 special token,是就 `stoi[piece]`,否则才逐字。',
    '',
    '**坑 2:Dropout 在 SFT 里开太大模型背不住样本**',
    '',
    'v0.8 配的 dropout=0.1 在预训刚好,SFT 阶段样本只有 37k 比预训少 50×,dropout 太大会让模型记不住格式。可以试 dropout=0.05 看看 val 是不是更低。',
    '',
    '**坑 3:pad_id 选了一个数据里出现过的 ID → 模型把 pad 当真信号学**',
    '',
    '我们用 `<|pad|>` 这种独立 token,id=14481,数据里绝不会自然出现。**绝对不能**拿 0 (某个汉字的 ID) 当 pad。',
    '',
    '**坑 4:迁移权重时手抖把 `key in (...)` 改成 `key == ...` 漏了 lm_head**',
    '',
    'lm_head 和 token_embedding 都需要前 14477 行特殊处理 —— 这两个都是 `(vocab_size, n_embed)` shape。漏一个 → 新 token 的 logits 永远 garbage。',
    '',
    '**坑 5:generate 时 prompt 编码忘了加 `<|开始|>`**',
    '',
    'prompt 必须以 `<|开始|>` 结尾,模型才知道"现在该输出正文了"。漏了 → 模型继续生成"风格"槽位的内容,胡言乱语。',
),

md(
    '## 7. 进入 Week 7 前',
    '',
    '现在你应该:',
    '- ☑ `tokenizer_v3.pkl` 和 `sft_data.pt` 都存在',
    '- ☑ `checkpoints/v09_sft/best.pt` 存在',
    '- ☑ `--battery` 跑出来 A 档(古典)能写出 4 句押韵的诗,D 档(996)很搞笑',
    '- ☑ 能解释 prompt mask 的"为什么 -100 而不是 0"',
    '',
    'Week 7 我们要在 SFT 之上再加一层 **DPO 偏好对齐**:用规则评分器(押韵 / 句数 / 题目相关)自动给候选打分,代替昂贵的人工 RLHF。这是 SFT → "更对齐人类偏好"的关键一步。',
),

]

save('06_sft_instruction_tuning.ipynb', W6)


# ============================================================
# Week 7 · DPO 偏好对齐
# ============================================================
W7 = [

md(
    '# Week 7 · DPO 偏好对齐',
    '',
    '> **本周一句话**:用规则评分器自动标偏好对(chosen vs rejected),用 DPO loss 把 v0.9 升级到 v0.10 —— 不训独立 reward model,直接让 policy 学会偏好。',
    '',
    '这周难点是**理解 DPO 的数学**(为什么这个 loss 等价于 RLHF)和**正确的 ref_model 用法**(eval / train 模式切换是常见 bug)。',
),

md(
    '## 0. 本周目标',
    '',
    '| 阶段 | 数据 | 方法 | 产出 |',
    '|---|---|---|---|',
    '| 评分器 | — | pypinyin 提韵尾、句数/字数判定 | `evaluation/score.py` |',
    '| 数据构造 | SFT val 中 1000 个 prompt × 4 候选 | 排序选最高最低分,过滤分差 < 5 | ~500 对 (chosen, rejected) |',
    '| DPO 训练 | 上述偏好对 | 500 步,lr=1e-5,β=0.1 | v0.10 |',
    '| 评估 | 6 题 head-to-head | 同种子比 v0.9 vs v0.10 | win/lose/tie |',
    '',
    '**val loss 概念变化**:不再是"语言模型 loss",而是 DPO loss = `-log σ(β·margin)`。理想:< 0.69(= -log(0.5),代表模型至少能 50% 正确偏好 chosen)。',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 6 SFT 跑通,v0.9 能按题目+风格生成',
    '- 知道 RLHF 是什么(reward model + PPO 的传统流程)',
    '',
    '**这周第一次遇到**:',
    '- `pypinyin` 库:从汉字提取韵母',
    '- DPO loss 公式与推导',
    '- "policy model" vs "reference model" 的概念',
    '- 训练时 train / eval 模式切换的微妙之处',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 RLHF 三步走 vs DPO 一步到位',
    '',
    '传统 RLHF(InstructGPT / ChatGPT 走的):',
    '',
    '```',
    'SFT → 训 Reward Model → 用 PPO 优化 policy(以 RM 为奖励信号)',
    '```',
    '',
    '问题:',
    '- 需要训独立 RM(再多一个模型 + 数据)',
    '- PPO 调超参很难,训练不稳定',
    '',
    'DPO(Direct Preference Optimization,2023)证明:**给定偏好对 (chosen, rejected),可以直接优化 policy 而不显式训 RM**,数学上等价于 RM + KL 约束的最优解。',
    '',
    '一行 loss 公式:',
    '',
    '$$L_{\\mathrm{DPO}} = -\\log \\sigma\\left(\\beta \\cdot \\left(\\log\\frac{\\pi(c)}{\\pi_{\\mathrm{ref}}(c)} - \\log\\frac{\\pi(r)}{\\pi_{\\mathrm{ref}}(r)}\\right)\\right)$$',
    '',
    '直觉:让当前 policy 在 chosen 上的相对 log-prob(相对于 ref)比 rejected 高。**β 越大,模型越激进地偏好 chosen,但越容易偏离 ref(灾难性遗忘)**。我们用 β=0.1。',
),

md(
    '### 2.2 评分器是 DPO 的"老师"',
    '',
    '没有人工标注,我们用规则评分器:',
    '',
    '```python',
    'def score_poem(poem, target_style, target_title):',
    '    score = 0',
    '    # 1. 句数 4/8 对 → +10',
    '    # 2. 每句字数 5/7 对 → 每句 +2',
    '    # 3. 偶数句尾字押韵(pypinyin 提韵) → 每对 +4',
    '    # 4. 题目相关字出现 → 每个 +3',
    '    # 5. 无连续 3 次以上重复 → +3',
    '    return score',
    '```',
    '',
    '**评分器的智力上限就是 DPO 的上限**。我们的规则评分能识别格律 + 押韵 + 字面相关,但识别不了意境、情感、用典是否准确。所以 v0.10 在"形式"上会比 v0.9 好,在"意境"上未必。',
    '',
    'GPT-4-as-a-judge 是更强的自动评分,但本课程用规则版,可解释、可复现。',
),

md(
    '### 2.3 偏好对的构造',
    '',
    '```',
    'for prompt in 1000 个 prompts:',
    '    candidates = [SFT model 生成 N=4 次]   # T=1.0 + top_k=40,刻意高温度求多样性',
    '    打分排序',
    '    chosen   = 最高分',
    '    rejected = 最低分',
    '    if chosen.score - rejected.score >= 5:  # 必须有显著分差,否则跳过',
    '        save (chosen, rejected)',
    '```',
    '',
    '**关键设计**:',
    '- 温度 1.0 + top_k 40:刻意求多样性,4 个候选差别要大才能挑出"明显好"和"明显差"',
    '- 分差阈值 5:避免"两首差不多的诗"训成偏好对(噪声大,反而有害)',
    '- 用 SFT val 而不是 train 的 prompt:确保 prompt 不在 v0.9 训练分布里',
    '',
    '最终大约能收 500-700 对(取决于 SFT 模型质量和评分分布)。',
),

md(
    '### 2.4 ref_model 的角色',
    '',
    'DPO 需要两个模型:',
    '- **policy**(可训): 一开始是 v0.9 SFT,训练中被更新',
    '- **ref**(冻结): 一直是 v0.9 SFT 的快照,提供"原始概率"作为对比基准',
    '',
    '代码:',
    '',
    '```python',
    'model     = load_v09_sft()              # 待训',
    'ref_model = copy.deepcopy(model)         # 冻结',
    'ref_model.eval()',
    'for p in ref_model.parameters():',
    '    p.requires_grad = False',
    '```',
    '',
    '**为什么需要 ref**?',
    '- 直接最大化 log π(chosen) 会让模型走极端(永远只生成 chosen 那种格式)→ 失去多样性、灾难性遗忘',
    '- 用 `log π / π_ref` 做相对量,**相对** ref 的偏好提升 = 学到的是"偏好方向"而不是"绝对概率"',
    '- 数学上等价于"在 RM 优化目标里加一个 KL(π || π_ref) 约束",防止 policy 跑得太远',
),

md(
    '### 2.5 train / eval 模式的关键陷阱',
    '',
    '**最容易踩的坑**:dropout 开/关导致 ref 和 policy 算出不同 log-prob。',
    '',
    '```python',
    '# 训练循环里',
    'model.train()        # ← policy 开 Dropout (正常训练状态)',
    'loss, m = dpo_loss(model, ref_model, ...)',
    '',
    '# 评估循环里',
    'model.eval()         # ← policy 必须 eval,关 Dropout',
    'ref_model.eval()     # ← ref 永远 eval',
    'loss, m = dpo_loss(model, ref_model, ...)',
    '```',
    '',
    '**为什么训练时 policy 可以开 Dropout**?Dropout 引入正则,让 policy 不要 overfit 偏好对。但 ref 必须冻结(eval),否则 `model_sft.eval()` 调用同时影响 policy 和 ref(同一个对象的克隆,deepcopy 之后是独立的,但容易写错)。',
    '',
    '**初学者常犯**:整个训练循环 `model.train()` 一开到底,评估时也是 train 模式 → ref 和 policy 都开 Dropout → DPO loss 计算不一致。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `evaluation/score.py` | 90 | pypinyin 提韵 + 评分函数 |',
    '| `data/prepare_dpo.py` | 110 | 用 v0.9 生成 + 评分 → 偏好对 |',
    '| `train/dpo_loss.py` | 70 | `compute_logprobs` + `dpo_loss`,带 metrics |',
    '| `train/train_v10_dpo.py` | 175 | 完整训练循环,500 步 |',
    '| `inference/compare_dpo.py` | 60 | 同种子对比 v0.9 vs v0.10 |',
),

md(
    '## 4. 动手做',
),

code(
    'import subprocess',
    '',
    '# 1. 生成偏好对(~30 分钟 T4,大头是 SFT 模型推理)',
    'subprocess.run(["python", "../data/prepare_dpo.py"], check=True)',
    '# 预期:',
    '#   "采样 1000 个唯一 prompt"',
    '#   每 100 个 print 一次进度',
    '#   最终收 500-700 对,平均分差 8-12',
),

code(
    '# 2. DPO 训练(~5 分钟)',
    'subprocess.run(["python", "../train/train_v10_dpo.py"], check=True)',
    '# 预期:',
    '#   step 0 时 val loss ~0.69(随机猜对偏好的水平)',
    '#   收敛到 < 0.5,acc > 0.7',
),

code(
    '# 3. 同种子对比 v0.9 vs v0.10',
    'subprocess.run(["python", "../inference/compare_dpo.py"], check=True)',
    '# 预期: v10 在"形式合规"维度上 win 多 lose 少(评分器只衡量形式)',
    '#       意境层面 v9 / v10 可能各有千秋',
),

md(
    '## 5. 自测题',
    '',
    '**A. DPO 数学**',
    '- A1 推导:当 ref == policy 时,DPO loss 严格等于多少?为什么?',
    '- A2 β 从 0.1 改成 1.0,训练会有什么不同?极端情况 β = 10 呢?',
    '- A3 DPO loss 收敛到 0 意味着什么?健康吗?',
    '',
    '**B. 偏好对**',
    '- B1 评分器给 chosen 50 分、rejected 48 分,这样的对该不该用?为什么?',
    '- B2 N_CANDIDATES=4 改成 8 会怎样?改成 2 呢?',
    '- B3 评分器只看"形式"(押韵 / 句数),DPO 训完模型只能在形式上"更好"吗?能学到意境吗?',
    '',
    '**C. ref_model**',
    '- C1 为什么不能省略 ref_model,直接最大化 log π(chosen)?',
    '- C2 ref 用 v0.8(预训练)而不是 v0.9(SFT)会怎样?',
    '- C3 训练过程中能不能定期把 policy 复制成新的 ref?(这叫 iterative DPO)',
    '',
    '**D. 工程**',
    '- D1 评估时 `model_sft.eval()` 但忘了切回 train,接下来训练循环会怎样?',
    '- D2 训 500 步够用吗?训 5000 步会怎样?',
    '- D3 DPO weight_decay=0 不加权重衰减,原因?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:Dropout 开着评估 → DPO loss 不是 0.6931 (理论值)**',
    '',
    '在 sanity check 阶段(model_state == ref_state 时),如果不切 eval,Dropout 随机化让两边 logits 不一样,loss 会偏离 0.6931。**我们的代码在 estimate_dpo 开头显式 `model.eval()`**。',
    '',
    '**坑 2:`compute_logprobs` 对 padding 算了 loss**',
    '',
    '答案末尾 + pad 全要 mask 掉。我们的实现做了 `targets != pad_id` 的 mask。否则 pad 越多 loss 越虚高。',
    '',
    '**坑 3:偏好对的 prompt_lens 算错**',
    '',
    'compute_logprobs 里 mask 起点是 `prompt_lens - 1`(因为 per_token_logp 是错位的)。少 1 多 1 都会让 loss 算到 prompt 上(或漏算第一个答案 token)。',
    '',
    '**坑 4:训练 200 步后突然 grad_norm 飙到 30+**',
    '',
    'DPO 训练遇到几个"分差极大"的对时,梯度会突然变大。我们有 `clip_grad_norm_(1.0)` 兜底。但如果整体平均 grad_norm 都在涨,说明 β 太大或 lr 太大,要降。',
    '',
    '**坑 5:reward_chosen 涨,reward_rejected 没降 —— 模型学了"绝对偏好"而不是"相对偏好"**',
    '',
    'DPO 的健康曲线是:reward_chosen 涨,reward_rejected 跌,两者差 (margin) 越拉越大。如果只是 chosen 涨而 rejected 没动,说明 β 太小 / KL 约束太强,模型只往 chosen 拉但不敢拒绝 rejected。',
),

md(
    '## 7. 进入 Week 8 前',
    '',
    '现在你应该:',
    '- ☑ `dpo_data.pt` 存在,500-700 对偏好',
    '- ☑ `checkpoints/v10_dpo/best.pt` 存在',
    '- ☑ compare_dpo 跑出来 v10 评分 win > lose',
    '- ☑ 能在白板上推 DPO loss 公式(至少 ref==policy → 0.6931 这一步)',
    '',
    'Week 8 完全换赛道 —— 不再训我们自己的小模型,而是 4-bit 量化加载 Qwen-1.5B + LoRA 微调。**对照自己写的 25M 模型,看商业级模型差在哪**。',
),

]

save('07_dpo_preference_alignment.ipynb', W7)


# ============================================================
# Week 8 · QLoRA 微调 Qwen 1.5B
# ============================================================
W8 = [

md(
    '# Week 8 · QLoRA 微调 Qwen 1.5B',
    '',
    '> **本周一句话**:4-bit 量化加载 Qwen 2.5-1.5B-Instruct,只训 4.3M LoRA 参数(占总参 0.28%),在 T4 上 30 分钟教会它写古诗 —— 对照自己的 25M 模型,直观感受"商业级 vs 自己造"的差距。',
    '',
    '这是项目的收尾周。前 7 周你从零造了一个能写诗的小模型;本周用同样的数据微调一个"巨人",体感到 scale 和预训练数据的力量。',
),

md(
    '## 0. 本周目标',
    '',
    '| 维度 | 自家 v0.10 | Qwen + LoRA |',
    '|---|---|---|',
    '| 基座 | 从零训 | Qwen2.5-1.5B-Instruct(已预训 7T+ tokens) |',
    '| 参数 | 25 M 全部可训 | 1.5 B 总参 / **4.3 M 可训(LoRA only)** |',
    '| 显存 | 训练 ~1 GB | 训练 ~6 GB(4-bit base + fp32 LoRA) |',
    '| 数据 | 我们的唐宋诗词 | 同样,但转 Qwen chat 格式 |',
    '| 单条生成质量 | 押韵 OK,偶尔出金句 | 流畅、押韵、能写英→中、能写现代题材 |',
    '| 训练时间(T4)| 0.5 小时(SFT) | v1: 15 min,v2 继续: 30 min |',
    '',
    '产出:`checkpoints/qwen_lora_v1/` 和 `qwen_lora_v2/`,各约 40 MB(只是 LoRA 补丁,不是完整模型)。',
),

md(
    '## 1. 前置知识',
    '',
    '**必备**:',
    '- Week 6 SFT 跑完(理解 prompt mask、chat 格式)',
    '- 知道什么是 fp16 / fp32',
    '',
    '**这周第一次遇到**:',
    '- NF4 4-bit 量化(`bitsandbytes`)',
    '- LoRA 的数学:`W\' = W + (α/r) · BA`',
    '- `peft` 库(LoraConfig / get_peft_model / PeftModel)',
    '- `trl.SFTTrainer`(HuggingFace 的"开箱即用"训练器)',
    '- gradient_checkpointing(用计算换显存)',
    '- paged_adamw_8bit',
),

md(
    '## 2. 核心概念',
    '',
    '### 2.1 NF4 4-bit 量化(QLoRA 的 Q)',
    '',
    'Qwen 1.5B 原始 fp16 权重约 3 GB。NF4 把每个权重压成 4-bit,理论 4× 压缩 → ~750 MB。加上 scale / zero_point 等元数据,实际约 1.2 GB。',
    '',
    '**NF4(NormalFloat 4-bit)的设计**:',
    '- 神经网络权重大致正态分布',
    '- 普通 INT4 在正态分布上分辨率浪费(尾部值少但占 ID)',
    '- NF4 = 把 16 个量化级别按正态分布的 16 等分位点排布,信息论意义上最优',
    '',
    '**double_quant**:量化的 scale 本身也再量化一次,再省 10%。',
    '',
    '**关键限制**:4-bit 权重**不能直接训** —— 量化函数不可导。所以 QLoRA 用 LoRA 补丁来"绕开"。',
),

md(
    '### 2.2 LoRA 的数学(QLoRA 的 LoRA)',
    '',
    '对一个原始 `Linear: W ∈ ℝ^{d×k}`(比如 Qwen 的 q_proj),LoRA 加一个低秩补丁:',
    '',
    '$$W\' = W + \\frac{\\alpha}{r} \\cdot B A$$',
    '',
    'where:',
    '- `A ∈ ℝ^{r×k}`,标准正态初始化',
    '- `B ∈ ℝ^{d×r}`,**初始化为 0**(关键:开始时 BA=0,W\' = W,模型行为完全等同 base)',
    '- `r = 16`(秩),`α = 32`(scaling = α/r = 2)',
    '',
    '**参数量对比**:',
    '- 原 `W`: `d × k`(假设 1024×1024 = 1M)',
    '- LoRA `A + B`: `r × k + d × r` = 16×1024 + 1024×16 = 32K  → **省 30×**',
    '',
    '推理时可以选择 merge: `W ← W + (α/r)BA`,变回普通 Linear。我们的 `generate.py` 不 merge(用 PeftModel 包装),省事但稍慢。',
    '',
    '**target_modules = ["q_proj", "k_proj", "v_proj", "o_proj"]**:只贴在 attention 的 Q/K/V/O 上,不贴 MLP。LoRA 论文实验:Attention 是泛化的关键,LoRA 在 Attention 上的性价比最高。',
),

md(
    '### 2.3 FP32 LoRA + 4-bit base 的精度棋牌',
    '',
    '量化模型直接训会出问题。**正确做法**:',
    '',
    '```python',
    'model = prepare_model_for_kbit_training(model)   # peft 准备:启梯度检查点,fp16 norm 等',
    'model = get_peft_model(model, lora_config)       # 加 LoRA 补丁',
    '',
    '# 关键修复:LoRA 补丁手动转 FP32',
    'for _, p in model.named_parameters():',
    '    if p.requires_grad:',
    '        p.data = p.data.to(torch.float32)',
    '',
    '# SFTConfig 必须关 fp16 / bf16',
    'training_args = SFTConfig(fp16=False, bf16=False, ...)',
    '```',
    '',
    '**为什么不能开 AMP**?',
    '- base 权重已经是 4-bit(bnb_4bit_compute_dtype=fp16,反量化到 fp16 算 forward)',
    '- LoRA 补丁如果再走 fp16 → 梯度数值范围窄 → 训不动',
    '- 让 LoRA 走 fp32,与 4-bit base 配合 —— 这是 QLoRA 原论文的标准做法',
    '',
    '**SFTConfig 开 fp16=True 是最常见的错误**(因为大家训普通模型时都开)。我们 cell 9 就是这么错的,cell 10 才修对。',
),

md(
    '### 2.4 gradient_checkpointing + paged_adamw_8bit 进一步压显存',
    '',
    '**gradient_checkpointing**:不缓存中间 activation,反向时重新算一遍。',
    '- 显存:省 30-50%(activation 占大头)',
    '- 速度:慢 20-30%(多算一次 forward)',
    '- 对 T4 这种小显存卡,稳赢的交易',
    '',
    '**paged_adamw_8bit**:把 Adam 的 m/v 动量从 fp32 (4 bytes) 压到 8-bit (1 byte)。',
    '- 显存:m+v 状态省 4×',
    '- 精度:8-bit 动量基本不影响最终质量(bitsandbytes 论文验证)',
    '',
    '加上这两个,Qwen 1.5B + LoRA + batch=2 在 T4 上稳跑 6 GB。',
),

md(
    '### 2.5 v1 vs v2 训练策略',
    '',
    '**v1**:朴素采样 2000 条样本,2 epoch,lr=2e-4',
    '- 风格分布天然不均(七绝最多)',
    '- 模型会偏向七绝',
    '',
    '**v2**:均衡采样每种风格 1500 条 = 6000 条,3 epoch,lr=1e-4(基于 v1 继续训)',
    '- 五绝 / 七绝 / 五律 / 七律 各得到充分训练',
    '- lr 减半防止破坏 v1 学到的格律',
    '',
    '为什么不一步到位训 v2?教学价值:**先看到失败的偏好,再修**,理解平衡数据的必要性。',
),

md(
    '## 3. 代码地图',
    '',
    '| 文件 | 行数 | 干什么 |',
    '|---|---|---|',
    '| `qlora/load_qwen.py` | 45 | NF4 4-bit 加载 Qwen,~1.2 GB 显存 |',
    '| `qlora/zero_shot_baseline.py` | 75 | 微调前对照(6 题写诗 + 4 题英→中) |',
    '| `qlora/prepare_data.py` | 135 | 把 Week 6 SFT 数据转 Qwen chat 格式,支持 `--balanced` |',
    '| `qlora/train.py` | 160 | LoRA 训练,带 `--v2` 续训均衡数据 |',
    '| `qlora/generate.py` | 120 | 加载 LoRA + 生成,带 peft torchao patch |',
    '',
    '依赖比前 7 周重:`transformers + accelerate + bitsandbytes + peft + trl + datasets`,合计 ~2 GB 安装。',
),

md(
    '## 4. 动手做',
    '',
    '**先装 qlora 额外依赖**:',
    '',
    '```powershell',
    'uv sync --extra qlora',
    '```',
    '',
    '依赖装好后,激活 venv,按顺序跑:',
),

code(
    'import subprocess',
    '',
    '# 1. 看微调前 Qwen 写诗水平(基线,~5 分钟首次下载模型)',
    'subprocess.run(["python", "../qlora/zero_shot_baseline.py"], check=True)',
    '# 预期: Qwen 已经能写出像样的古诗,但格律偶尔出错',
    '#       英→中也能凑合写,但风格不够"唐诗味"',
),

code(
    '# 2. 准备 v1 数据(秒级)',
    'subprocess.run(["python", "../qlora/prepare_data.py"], check=True)',
    '# 预期: train=1900, val=100, Qwen chat 格式',
),

code(
    '# 3. v1 LoRA 训练(~15 分钟 T4)',
    'subprocess.run(["python", "../qlora/train.py"], check=True)',
    '# 预期:',
    '#   "可训参数: 4.30M / 总 1.54B (0.279%)"',
    '#   ~475 步训完',
    '#   eval_loss 从 1.5 降到 0.8 左右',
),

code(
    '# 4. 准备 v2 均衡数据',
    'subprocess.run(["python", "../qlora/prepare_data.py", "--balanced"], check=True)',
    '# 预期: train=5820, val=180, 每种风格 1500 条',
),

code(
    '# 5. v2 继续训(基于 v1 LoRA,~30 分钟)',
    'subprocess.run(["python", "../qlora/train.py", "--v2"], check=True)',
    '# 预期: lr=1e-4 比 v1 的 2e-4 小一倍,3 epoch ~2200 步',
),

code(
    '# 6. 看微调后效果',
    'subprocess.run(["python", "../qlora/generate.py", "--battery"], check=True)',
    '# 8 道题套件,对照前面 v0.9 / v0.10 写的同样题目',
),

code(
    '# 7. 记忆测试: 看模型是否在背训练集',
    'subprocess.run(["python", "../qlora/generate.py", "--memorize"], check=True)',
    '# 续写《静夜思》前两句。如果一字不差输出"举头望明月,低头思故乡"',
    '# = 模型在背诵训练集,过拟合了',
),

md(
    '## 5. 自测题',
    '',
    '**A. 量化**',
    '- A1 NF4 vs INT4 vs FP4 三种 4-bit 量化各自的特点?为什么 NF4 最适合权重?',
    '- A2 double_quant 把 scale 也量化,精度损失明显吗?',
    '- A3 量化后的模型推理慢还是快?为什么?',
    '',
    '**B. LoRA**',
    '- B1 r=16 vs r=8 vs r=64 各有什么取舍?',
    '- B2 α=2r 的经验从哪来?如果 α=r 会怎样?',
    '- B3 为什么只贴 q/k/v/o,不贴 MLP?如果全部贴呢?',
    '- B4 LoRA 的 B 初始化为 0 是关键设计,如果 B 初始化为随机正态会怎样?',
    '',
    '**C. QLoRA 精度组合**',
    '- C1 base 4-bit、LoRA fp32、forward 算什么精度?',
    '- C2 SFTConfig fp16=True + LoRA fp32 会怎样?(实际试过会 NaN)',
    '- C3 gradient_checkpointing 慢 20-30% 但显存省一半,什么时候不值得开?',
    '',
    '**D. 训练**',
    '- D1 paged_adamw_8bit 把动量压成 8-bit,会影响最终质量吗?哪些场景下风险大?',
    '- D2 v2 用 lr=1e-4(v1 的一半)续训,如果用 2e-4 会怎样?',
    '- D3 LoRA 只占总参 0.28%,但学到的"指令能力"为什么够用?',
),

md(
    '## 6. 容易踩的坑',
    '',
    '**坑 1:`SFTConfig(fp16=True)` + LoRA → NaN**',
    '',
    'cell 9 的朴素配置(没明确处理精度)会让 GradScaler 和 4-bit 量化打架,loss 几步内变 NaN。**修复**: `fp16=False, bf16=False`,LoRA 手动转 fp32。',
    '',
    '**坑 2:bitsandbytes 在 Windows 上装不上**',
    '',
    'bnb 0.43+ 官方支持 Windows,但要求 CUDA 11.7+。如果你 PyTorch 是 cu128,bnb 应该自动 OK。装不上的话:',
    '- 试 `pip install bitsandbytes-windows`(社区 fork)',
    '- 或者 Week 8 整个搬 Colab 跑',
    '',
    '**坑 3:`peft` 加载 LoRA 时报 `torchao` 错**',
    '',
    'peft 0.12+ 启动时会探测 torchao,某些环境探测失败。我们的 `qlora/generate.py:_patch_peft_torchao` monkey-patch 关掉这个探测。如果你看到 `is_torchao_available` 报错,确认 patch 被调用。',
    '',
    '**坑 4:Qwen tokenizer 用 chat_template 时漏掉 `add_generation_prompt=True`**',
    '',
    '训练时:`add_generation_prompt=False`(完整对话)',
    '推理时:`add_generation_prompt=True`(到 `<|im_start|>assistant\\n` 截断,让模型从这里开始生成)',
    '',
    '漏了 → 推理时模型可能"补全 user 输入"而不是回答。',
    '',
    '**坑 5:保存 LoRA 后误以为是完整模型,删了 Qwen base → 推理时 base 重新下载 3 GB**',
    '',
    'LoRA 保存的只是 ~40 MB 的补丁,推理时必须配合 base 一起加载。HuggingFace cache 默认在 `~/.cache/huggingface/`,清这个会触发重新下载。',
),

md(
    '## 7. 项目结业',
    '',
    '现在你应该:',
    '- ☑ `checkpoints/qwen_lora_v1/` 和 `v2/` 都存在',
    '- ☑ `--battery` 跑出来 Qwen LoRA 写的诗明显比自家 v0.10 更流畅',
    '- ☑ 能解释 QLoRA = "4-bit base + LoRA fp32 + 关 AMP" 这三件套',
    '- ☑ 能解释为什么 0.28% 的可训参数能改变模型行为(LoRA 的低秩假设)',
    '',
    '## 8 周回顾',
    '',
    '| Week | 学到什么 |',
    '|---|---|',
    '| 1 | 数据 pipeline 的工程纪律 |',
    '| 2 | Transformer 全套组件,Bigram → 6 层 GPT |',
    '| 3 | LR schedule、AMP、grad clip、wd —— 工业级训练循环 |',
    '| 4 | Checkpoint 系统、断点续训、TensorBoard 监控 |',
    '| 5 | 数据 + 模型双扩,scaling law 的初步体感 |',
    '| 6 | SFT、特殊 token、prompt mask、vocab 扩展权重迁移 |',
    '| 7 | DPO 数学、自动评分、ref_model 概念 —— 不用 RLHF 也能对齐 |',
    '| 8 | QLoRA = 4-bit + LoRA,在小显存上微调真实大模型 |',
    '',
    '你现在掌握的工具栈,**和 2024 年开源 LLM 训练社区的主流栈差不多**。再往下走的方向:',
    '- **分布式训练**:多卡 DDP / FSDP / DeepSpeed(数据 ~100B 起步)',
    '- **MoE**:Mixtral 类型的稀疏激活',
    '- **Long context**:RoPE / YaRN 把 context 推到 32K+',
    '- **更高级对齐**:GRPO(DeepSeek)、KTO、IPO 等 DPO 变种',
    '- **推理优化**:vLLM / PagedAttention / 量化推理',
    '',
    '但所有这些都建立在你前 8 周打的基础上。**收工**。',
),

]

save('08_qlora_qwen_finetune.ipynb', W8)


if __name__ == '__main__':
    print('Week 5-8 课程文件生成完毕')
